/**
 * RPG Maker MZ - Complete DLC Database
 * Data sourced from Steam store, SteamDB, community reviews, and RPG Maker forums.
 * Last updated: 2026-08-05
 *
 * Price data: CNY (Chinese Yuan / 人民币)
 * - price_cny: Current Steam CN region price
 * - price_cny_lowest: Historical lowest recorded price (via SteamDB / DekuDeals)
 */

const ALL_DLCS = [
  // ============================================================
  // 🔌 PLUGINS / 插件工具
  // ============================================================
  {
    id: "plugin-card-deckbuilder",
    title_en: "Card Game Combat Deckbuilder Engine",
    title_zh: "卡牌战斗卡组构筑引擎",
    category: "plugin",
    sub_category: "Battle System",
    rating: 4.8,
    steam_rating: 95,
    price_cny: 98,
    price_cny_lowest: 78,
    steam_url: "https://store.steampowered.com/app/3243580/",
    steam_verified: true,
    steam_appid: "3243580",
    description: "将RPG Maker MZ默认回合制战斗转换为Roguelike卡组构筑系统。技能列表变为卡牌组，支持抽牌、弃牌、洗牌等机制。包含卡牌自定义模板、卡牌商店和卡组编辑器扩展插件。附带完整演示项目和模板。",
    review_summary: "社区高度评价，被认为是MZ最具变革性的战斗插件之一。学习曲线适中，但成品效果极佳。适合制作类Slay the Spire风格RPG。",
    theme: "卡牌/策略",
    tags: ["卡牌", "deckbuilder", "roguelike", "战斗系统", "TCG", "策略"],
    gameplay_features: ["卡组构筑", "抽牌/弃牌机制", "自定义卡牌外观", "卡牌商店", "装备卡牌", "连击系统"],
    screenshots: ["https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/3243580/ss_e74381ebbf4882e150da4d3cb14962466c437796.1920x1080.jpg"]
  },
  {
    id: "plugin-srpg-gear",
    title_en: "SRPG Gear MZ - Tactical Battle System",
    title_zh: "SRPG Gear MZ - 战棋战术战斗系统",
    category: "plugin",
    sub_category: "Battle System",
    rating: 4.5,
    steam_rating: 90,
    price_cny: 0,
    price_cny_lowest: 0,
    steam_url: "https://store.steampowered.com/app/2811870/",
    steam_verified: true,
    steam_appid: "2811870",
    description: "免费DLC！为RPG Maker MZ添加战棋/SRPG战术战斗系统。无需编程即可制作火焰纹章、皇家骑士团风格的战棋游戏。包含15+插件，支持范围控制、AOE技能、敌方AI、地形效果和单位召唤。",
    review_summary: "免费且功能强大，社区一致推荐。更新频繁，开发者活跃。适合制作战棋RPG的首选工具。",
    theme: "战棋/策略",
    tags: ["战棋", "SRPG", "战术", "免费", "火焰纹章", "地形效果", "网格战斗"],
    gameplay_features: ["网格移动", "范围技能", "敌方AI", "地形效果", "单位召唤", "AOE攻击", "回合制战术"]
  },
  {
    id: "plugin-action-combat",
    title_en: "RPG Maker Action Combat Plugin",
    title_zh: "RPG Maker 动作战斗插件",
    category: "plugin",
    sub_category: "Battle System",
    rating: 4.3,
    steam_rating: 85,
    price_cny: 235,
    price_cny_lowest: 188,
    steam_url: "https://store.steampowered.com/app/4417270/",
    steam_verified: true,
    steam_appid: "4417270",
    description: "官方动作战斗系统插件！将回合制战斗转变为实时动作战斗。支持8方向移动、近战/远程/AOE攻击、跳跃闪避、敌人AI追击。深度属性整合，元素克制系统。",
    review_summary: "MZ最受期待的动作战斗插件，价格较高但功能强大。适合制作ARPG（类似伊苏、塞尔达风格）。需要一定的插件配置经验。",
    theme: "动作/ARPG",
    tags: ["ARPG", "动作战斗", "实时战斗", "8方向移动", "闪避", "连击"],
    gameplay_features: ["实时动作战斗", "8方向移动", "近战/远程/AOE", "跳跃闪避", "元素克制", "装备即时切换"]
  },
  {
    id: "plugin-press-team",
    title_en: "Press Team Battle System Plugin",
    title_zh: "Press Team 战斗系统插件",
    category: "plugin",
    sub_category: "Battle System",
    rating: 4.2,
    steam_rating: 88,
    price_cny: 118,
    price_cny_lowest: 94,
    steam_url: "https://store.steampowered.com/app/4894460/",
    steam_verified: true,
    steam_appid: "4894460",
    description: "基于真女神转生/Persona系列的Press Turn战斗系统。打击弱点获得额外行动次数，被抵抗则减少行动。策略性极强的回合制变体。",
    review_summary: "Persona系列粉丝的梦想插件。实现质量高，与MZ原生系统兼容良好。适合制作有深度的回合制战斗RPG。",
    theme: "策略回合制",
    tags: ["Persona", "真女神转生", "Press Turn", "弱点系统", "回合制", "策略"],
    gameplay_features: ["弱点打击奖励", "额外行动次数", "属性克制", "连击奖励", "敌我交互"]
  },
  {
    id: "plugin-timed-input",
    title_en: "Timed Input Plugin",
    title_zh: "节奏输入插件",
    category: "plugin",
    sub_category: "Battle System",
    rating: 4.0,
    steam_rating: 82,
    price_cny: 76,
    price_cny_lowest: 61,
    steam_url: "https://store.steampowered.com/app/4603320/",
    steam_verified: true,
    steam_appid: "4603320",
    description: "为战斗添加节奏/QTE元素。精确时机按键获得伤害加成，失误则减少效果。类似马力欧RPG或音游与RPG的混合体验。",
    review_summary: "为传统回合制增加操作感和紧张感。配置灵活，可调节难度。适合想要更多玩家互动的回合制RPG。",
    theme: "节奏/互动",
    tags: ["QTE", "节奏", "时机", "按键", "互动", "操作感"],
    gameplay_features: ["精准时机判定", "伤害倍率", "连击奖励", "难度可调", "视觉反馈"]
  },
  {
    id: "plugin-light-shadow",
    title_en: "Light and Shadow Plugin",
    title_zh: "光影系统插件",
    category: "plugin",
    sub_category: "Visual",
    rating: 4.5,
    steam_rating: 92,
    price_cny: 88,
    price_cny_lowest: 70,
    steam_url: "https://store.steampowered.com/app/4513430/",
    steam_verified: true,
    steam_appid: "4513430",
    description: "动态光影系统。根据游戏内天气和时间自动变化。支持动态阴影投射、点光源、环境光调节。大幅提升画面氛围和沉浸感。",
    review_summary: "画面效果提升显著，被多家开发者推荐。性能优化良好，对低配设备友好。配合暗黑风格地图效果极佳。",
    theme: "视觉增强/光影",
    tags: ["光影", "动态光源", "阴影", "天气", "昼夜", "氛围"],
    gameplay_features: ["动态光照", "实时阴影", "天气联动", "昼夜循环", "点光源", "环境光"]
  },
  {
    id: "plugin-sv-equip",
    title_en: "SV Equip Sprite Expansion Plugin",
    title_zh: "SV装备精灵扩展插件",
    category: "plugin",
    sub_category: "Visual",
    rating: 4.3,
    steam_rating: 87,
    price_cny: 66,
    price_cny_lowest: 53,
    steam_url: "https://store.steampowered.com/app/4112880/",
    steam_verified: true,
    steam_appid: "4112880",
    description: "强化侧视战斗视觉效果！每种武器绑定独特动画，装备外观实时反映在角色精灵上。支持武器、盾牌、盔甲、头盔等可视化装备系统。",
    review_summary: "为侧视战斗增加大量视觉细节。与SV生成器素材配合完美。配置简单但效果显著。",
    theme: "视觉/装备",
    tags: ["侧视战斗", "装备可视化", "精灵", "动画", "武器", "盔甲"],
    gameplay_features: ["装备外观显示", "武器专属动画", "盾牌显示", "盔甲可视化", "角色精灵绑定"]
  },
  {
    id: "plugin-fv-animations",
    title_en: "FV Actor Animations Plugin",
    title_zh: "正视图角色动画插件",
    category: "plugin",
    sub_category: "Visual",
    rating: 4.0,
    steam_rating: 83,
    price_cny: 66,
    price_cny_lowest: 53,
    steam_url: "https://store.steampowered.com/app/4024310/",
    steam_verified: true,
    steam_appid: "4024310",
    description: "为正视战斗添加角色动画、伤害弹出数字和精灵战斗者。让传统的正视图战斗焕发新生，更加生动。",
    review_summary: "怀旧向插件，为正视战斗增加现代视觉元素。适合喜欢经典DQ风格但想要更好视觉效果的开发者。",
    theme: "视觉/正视图战斗",
    tags: ["正视战斗", "角色动画", "伤害弹出", "精灵", "DQ风格"],
    gameplay_features: ["角色攻击动画", "伤害数字弹出", "精灵战斗者", "视觉反馈增强"]
  },
  {
    id: "plugin-free-arpg",
    title_en: "Free ARPG Plug-in Set",
    title_zh: "免费ARPG插件套装",
    category: "plugin",
    sub_category: "Battle System",
    rating: 3.8,
    steam_rating: 78,
    price_cny: 0,
    price_cny_lowest: 0,
    steam_url: "https://store.steampowered.com/app/2287820/",
    steam_verified: true,
    steam_appid: "2287820",
    description: "免费ARPG插件及配套图形素材。基本的动作战斗功能，适合入门和原型开发。2023年RPG Maker Festival期间发布。",
    review_summary: "作为免费DLC性价比极高。功能较为基础，但适合学习和快速原型。如需高级功能建议升级到付费动作战斗插件。",
    theme: "动作/免费",
    tags: ["ARPG", "免费", "动作战斗", "入门", "原型"],
    gameplay_features: ["基础动作战斗", "图形素材", "入门模板"]
  },
  {
    id: "plugin-rhythm-game",
    title_en: "Rhythm Game Maker",
    title_zh: "节奏游戏制作器",
    category: "plugin",
    sub_category: "Minigame",
    rating: 4.1,
    steam_rating: 84,
    price_cny: 76,
    price_cny_lowest: 61,
    steam_url: "https://store.steampowered.com/app/4099620/",
    steam_verified: true,
    steam_appid: "4099620",
    description: "将节奏游戏机制整合到RPG Maker中。战斗中得分影响技能伤害。可制作独立的音游或节奏RPG混合玩法。",
    review_summary: "独特的跨类型插件。对音游爱好者来说创意十足。需要配合合适的音乐素材使用效果最佳。",
    theme: "节奏/音游",
    tags: ["音游", "节奏", "音乐", "得分系统", "混合玩法"],
    gameplay_features: ["节奏判定", "计分系统", "技能伤害关联", "节拍同步", "音游UI"]
  },
  {
    id: "plugin-windowset-builder",
    title_en: "Windowset Builder",
    title_zh: "窗口皮肤编辑器",
    category: "plugin",
    sub_category: "Tool",
    rating: 4.2,
    steam_rating: 86,
    price_cny: 76,
    price_cny_lowest: 61,
    steam_url: "https://store.steampowered.com/app/4837660/",
    steam_verified: true,
    steam_appid: "4837660",
    description: "可视化窗口皮肤编辑器。无需编程即可自定义游戏所有UI窗口外观。调整颜色、边框、透明度、字体等，实时预览效果。",
    review_summary: "UI定制利器。比手动编辑图片高效很多。适合为每个游戏打造独特UI风格的开发者。",
    theme: "UI/工具",
    tags: ["窗口皮肤", "UI", "可视化编辑", "自定义", "界面"],
    gameplay_features: ["窗口外观编辑", "实时预览", "配色方案", "字体设置", "导出导入"]
  },
  {
    id: "plugin-tileset-builder",
    title_en: "Tileset Builder — Pixel Art Editor for Tiles & Sprites",
    title_zh: "图块编辑器 — 像素画图块与精灵编辑",
    category: "plugin",
    sub_category: "Tool",
    rating: 4.4,
    steam_rating: 89,
    price_cny: 88,
    price_cny_lowest: 70,
    steam_url: "https://store.steampowered.com/app/4691700/",
    steam_verified: true,
    steam_appid: "4691700",
    description: "完整的像素画编辑器，专为RPG Maker MZ/MV兼容图块和精灵设计。内置模板、图层系统和MZ格式导出功能。",
    review_summary: "填补了RPG Maker生态中编辑工具的空白。比外部像素编辑软件更方便，直接兼容MZ格式。",
    theme: "像素/编辑工具",
    tags: ["像素画", "图块编辑", "精灵编辑", "工具", "像素艺术"],
    gameplay_features: ["像素编辑", "图块模板", "图层系统", "MZ格式导出", "精灵制作"]
  },

  // ============================================================
  // 🗺️ TILESETS / 图块素材
  // ============================================================
  {
    id: "tileset-fsm-town",
    title_en: "FSM: Town of Beginning",
    title_zh: "FSM: 起始之镇",
    category: "tileset",
    sub_category: "Fantasy/Town",
    rating: 4.7,
    steam_rating: 94,
    price_cny: 92,
    price_cny_lowest: 28,
    steam_url: "https://store.steampowered.com/app/1441910/",
    steam_verified: true,
    steam_appid: "1441910",
    description: "精美的手绘风格城镇图块素材。包含完整的起始城镇地图模板、室内外装饰、角色行走图。色调略深于默认RTP，物品比例偏向MZ风格（稍大）。含夜晚版本地图。",
    review_summary: "社区公认最优秀的城镇图块DLC之一。FSM系列品质标杆。打折时性价比极高（史低70%off）。约80%与RTP兼容。",
    theme: "奇幻/城镇",
    tags: ["城镇", "FSM", "手绘", "模板", "夜晚", "RTP兼容", "日式奇幻"],
    gameplay_features: ["预置地图", "夜晚版本", "室内外", "NPC角色", "装饰物"],
    steam_screenshots: ["ss_0d57643e797923a5b83450f30e12c27e7d7d16aa.1920x1080.jpg"]
  },
  {
    id: "tileset-fsm-castle",
    title_en: "FSM: Castle and Town",
    title_zh: "FSM: 城堡与城镇",
    category: "tileset",
    sub_category: "Fantasy/Castle",
    rating: 4.6,
    steam_rating: 92,
    price_cny: 92,
    price_cny_lowest: 37,
    steam_url: "https://store.steampowered.com/app/1441930/",
    steam_verified: true,
    steam_appid: "1441930",
    description: "FSM系列城堡主题图块。宏伟的城堡建筑、王座厅、城墙、塔楼等经典奇幻场景。包含中世纪城镇配套素材。高品质手绘风格。",
    review_summary: "FSM系列又一力作。城堡素材细节丰富，适合制作王国/皇室主题游戏。与FSM: Town of Beginning配合使用效果更佳。",
    theme: "奇幻/城堡",
    tags: ["城堡", "FSM", "中世纪", "王座厅", "城墙", "塔楼", "奇幻"],
    gameplay_features: ["预置城堡地图", "室内外", "防御工事", "王室场景"]
  },
  {
    id: "tileset-fsm-woods",
    title_en: "FSM: Woods and Cave",
    title_zh: "FSM: 森林与洞穴",
    category: "tileset",
    sub_category: "Fantasy/Nature",
    rating: 4.5,
    steam_rating: 90,
    price_cny: 92,
    price_cny_lowest: 37,
    steam_url: "https://store.steampowered.com/app/1441920/",
    steam_verified: true,
    steam_appid: "1441920",
    description: "FSM系列自然场景图块。茂密森林、幽深洞穴、地下迷宫等。含丰富的植物、岩石、矿物素材和预置地图。",
    review_summary: "自然场景必备。洞穴素材尤其出色，层次感强。森林素材颜色丰富，适合制作探索类RPG。",
    theme: "奇幻/自然",
    tags: ["森林", "洞穴", "FSM", "自然", "地下城", "探索"],
    gameplay_features: ["预置地图", "多层洞穴", "植被丰富", "地下迷宫"]
  },
  {
    id: "tileset-fsm-desert",
    title_en: "FSM: Desert Town and Ruins",
    title_zh: "FSM: 沙漠城镇与遗迹",
    category: "tileset",
    sub_category: "Fantasy/Desert",
    rating: 4.4,
    steam_rating: 88,
    price_cny: 92,
    price_cny_lowest: 37,
    steam_url: "https://store.steampowered.com/app/1617520/",
    steam_verified: true,
    steam_appid: "1617520",
    description: "FSM系列沙漠主题。沙漠城镇、古代遗迹、金字塔、绿洲等。独特的沙土色调和风化建筑风格。",
    review_summary: "填补了RPG Maker沙漠主题的空缺。遗迹素材适合制作探索解密类地图。色调统一，风格独特。",
    theme: "沙漠/遗迹",
    tags: ["沙漠", "遗迹", "FSM", "金字塔", "绿洲", "探索"],
    gameplay_features: ["沙漠城镇", "古代遗迹", "金字塔内部", "沙地效果"]
  },
  {
    id: "tileset-trinity",
    title_en: "MV Trinity Resource Pack",
    title_zh: "MV Trinity 资源包",
    category: "tileset",
    sub_category: "Fantasy/Mixed",
    rating: 4.8,
    steam_rating: 95,
    price_cny: 138,
    price_cny_lowest: 62,
    steam_url: "https://store.steampowered.com/app/1351010/",
    steam_verified: true,
    steam_appid: "1351010",
    description: "MZ必入资源包之一！130+图块集、大量面孔、角色、音频和敌人战斗图。涵盖埃及、蒸汽朋克、东方风格。100%与MZ/MV RTP兼容。本质上是RTP的超级扩展包，提供大量变体和重新配色。",
    review_summary: "社区评价最高的通用资源包。内容量极大，单是图块就值回票价。与默认RTP无缝衔接，适合任何类型RPG。史低折扣力度大。",
    theme: "奇幻/多样化",
    tags: ["Trinity", "RTP扩展", "埃及", "蒸汽朋克", "东方", "综合", "必入"],
    gameplay_features: ["130+图块", "面孔素材", "角色行走图", "BGM", "敌人战斗图"],
    screenshots: ["https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1351010/ss_393b16f2d35871348353247158eb429b98ff2d48.1920x1080.jpg"]
  },
  {
    id: "tileset-ds-resource",
    title_en: "DS Resource Pack",
    title_zh: "DS 资源包",
    category: "tileset",
    sub_category: "Fantasy/Mixed",
    rating: 4.5,
    steam_rating: 91,
    price_cny: 138,
    price_cny_lowest: 62,
    steam_url: "https://store.steampowered.com/app/1350970/",
    steam_verified: true,
    steam_appid: "1350970",
    description: "从Nintendo DS版RPG Maker移植的高质量资源包。大量图块、角色、怪物素材。独特的上屏/下屏风格。数量丰富，涵盖多个主题。",
    review_summary: "DS版的经典素材合集。像素风格独特，适合制作复古/怀旧风格RPG。素材量足，性价比高。",
    theme: "像素/DS风格",
    tags: ["DS", "像素", "复古", "综合素材", "双屏"],
    gameplay_features: ["图块集", "角色素材", "怪物图", "DS风格"]
  },
  {
    id: "tileset-fes-resource",
    title_en: "FES Resource Pack",
    title_zh: "FES 资源包",
    category: "tileset",
    sub_category: "Fantasy/Mixed",
    rating: 4.3,
    steam_rating: 87,
    price_cny: 138,
    price_cny_lowest: 62,
    steam_url: "https://store.steampowered.com/app/1350930/",
    steam_verified: true,
    steam_appid: "1350930",
    description: "从3DS版RPG Maker FES移植的资源包。包含独特的图块、角色和音效素材。色彩明亮鲜艳，适合轻松愉快的RPG风格。",
    review_summary: "FES移植版，色彩风格活泼。适合制作轻松向、全龄向RPG。与MV/MZ RTP风格略有不同但可混搭。",
    theme: "明亮/休闲",
    tags: ["FES", "3DS", "明亮", "休闲", "轻松", "彩色"],
    gameplay_features: ["图块集", "角色素材", "音效", "明亮风格"]
  },
  {
    id: "tileset-train",
    title_en: "Add-on Vol.3: Train Tileset",
    title_zh: "附加包 Vol.3: 火车图块",
    category: "tileset",
    sub_category: "Steampunk/Vehicle",
    rating: 4.1,
    steam_rating: 85,
    price_cny: 48,
    price_cny_lowest: 24,
    steam_url: "https://store.steampowered.com/app/1350940/",
    steam_verified: true,
    steam_appid: "1350940",
    description: "蒸汽火车主题图块素材。包含火车头、车厢内部、铁轨、车站等完整素材。适合制作火车旅行、东方快车风格的场景。",
    review_summary: "主题明确，质量不错。火车内部细节丰富。适合特定场景但通用性一般。",
    theme: "蒸汽火车/交通",
    tags: ["火车", "蒸汽", "铁轨", "车站", "交通工具", "车厢"],
    gameplay_features: ["火车内饰", "铁轨系统", "车站", "交通工具"]
  },
  {
    id: "tileset-neonpixel-fairytale",
    title_en: "NEONPIXEL - ANIME FAIRYTALE VALLEY SET",
    title_zh: "NEONPIXEL - 动漫童话山谷套装",
    category: "tileset",
    sub_category: "Fantasy/Anime",
    rating: 4.4,
    steam_rating: 88,
    price_cny: 76,
    price_cny_lowest: 61,
    steam_url: "https://store.steampowered.com/app/4894340/",
    steam_verified: true,
    steam_appid: "4894340",
    description: "日式动漫风格的童话山谷图块。和平村庄、自然景观、花朵草地。明亮可爱的色调，适合轻松治愈系RPG。",
    review_summary: "画风极其可爱，日系动漫风格鲜明。适合制作治愈系、休闲向RPG。与默认素材风格差异较大但自成一体。",
    theme: "动漫/童话",
    tags: ["动漫", "童话", "山谷", "治愈", "可爱", "日系"],
    gameplay_features: ["童话村庄", "自然景观", "花卉草地", "明亮色调"]
  },
  {
    id: "tileset-cn-style",
    title_en: "CN-STYLE Tileset Collection",
    title_zh: "中国风图块合集",
    category: "tileset",
    sub_category: "Asian/Chinese",
    rating: 4.5,
    steam_rating: 90,
    price_cny: 98,
    price_cny_lowest: 78,
    steam_url: "https://store.steampowered.com/app/4894310/",
    steam_verified: true,
    steam_appid: "4894310",
    description: "大体量东亚/中国风主题图块包。包含村落、竹林、市集、宫殿、寺庙、园林等经典场景。细节丰富，文化元素准确。",
    review_summary: "中国风RPG的必备DLC。文化元素还原度高，素材量大。是目前MZ最完整的东亚风格图块包。",
    theme: "中国风/东亚",
    tags: ["中国风", "东方", "竹林", "宫殿", "寺庙", "园林", "武侠"],
    gameplay_features: ["中式建筑", "竹林场景", "市集", "宫殿内部", "园林景观"]
  },
  {
    id: "tileset-kr-wrath-volcano",
    title_en: "KR Wrath of the Volcano Tileset",
    title_zh: "KR 火山之怒图块",
    category: "tileset",
    sub_category: "Fantasy/Volcano",
    rating: 4.2,
    steam_rating: 86,
    price_cny: 62,
    price_cny_lowest: 53,
    steam_url: "https://store.steampowered.com/app/3903350/",
    steam_verified: true,
    steam_appid: "3903350",
    description: "Kokoro Reflections出品的火山主题图块。岩浆河流、火山洞穴、火焰神殿等。动态岩浆动画和灼热氛围。",
    review_summary: "KR系列品质稳定。火山主题独特，动画效果加分。适合制作火焰地下城和BOSS战场景。",
    theme: "火山/火焰",
    tags: ["火山", "岩浆", "KR", "火焰", "地下城", "BOSS场景"],
    gameplay_features: ["动态岩浆", "火焰神殿", "火山洞穴", "灼热氛围"]
  },
  {
    id: "tileset-kr-holy-cathedral",
    title_en: "KR Holy Saints Cathedral Tileset",
    title_zh: "KR 圣者大教堂图块",
    category: "tileset",
    sub_category: "Fantasy/Religious",
    rating: 4.4,
    steam_rating: 89,
    price_cny: 56,
    price_cny_lowest: 39,
    steam_url: "https://store.steampowered.com/app/2711870/",
    steam_verified: true,
    steam_appid: "2711870",
    description: "宏伟的哥特式大教堂图块。彩色玻璃窗、管风琴、圣坛、钟楼等。庄严神圣的氛围，适合制作教会/圣骑士主题场景。",
    review_summary: "KR系列中评价最高的之一。教堂细节精美，彩色玻璃特效出色。神圣氛围营造到位。",
    theme: "哥特/宗教",
    tags: ["教堂", "哥特", "KR", "彩色玻璃", "神圣", "宗教"],
    gameplay_features: ["大教堂", "彩色玻璃窗", "管风琴", "圣坛", "钟楼"]
  },
  {
    id: "tileset-kr-mars-colony",
    title_en: "KR Mars Colony Tileset",
    title_zh: "KR 火星殖民地图块",
    category: "tileset",
    sub_category: "Sci-Fi/Space",
    rating: 4.3,
    steam_rating: 87,
    price_cny: 66,
    price_cny_lowest: 53,
    steam_url: "https://store.steampowered.com/app/4125040/",
    steam_verified: true,
    steam_appid: "4125040",
    description: "科幻火星殖民地场景。室内舱室、温室穹顶、动画气闸门、火星车等。完整的科幻生存探索场景。",
    review_summary: "硬科幻风格难得一见。火星场景设计专业，细节到位。适合制作科幻生存/探索RPG。",
    theme: "科幻/火星",
    tags: ["火星", "科幻", "KR", "太空", "殖民地", "探索"],
    gameplay_features: ["气闸动画", "温室穹顶", "火星车", "太空舱", "红色沙漠"]
  },
  {
    id: "tileset-kr-spirit-germany",
    title_en: "KR Spirit of Germany Tileset",
    title_zh: "KR 德国之魂图块",
    category: "tileset",
    sub_category: "Real World/European",
    rating: 4.1,
    steam_rating: 84,
    price_cny: 66,
    price_cny_lowest: 59,
    steam_url: "https://store.steampowered.com/app/4228050/",
    steam_verified: true,
    steam_appid: "4228050",
    description: "德国风情建筑图块。巴伐利亚风格房屋、城堡、圣诞市场、啤酒馆等。欧洲小镇的韵味。",
    review_summary: "真实世界风格图块。德国建筑特色到位。适合制作以欧洲为背景的冒险RPG。",
    theme: "欧洲/德国",
    tags: ["德国", "欧洲", "KR", "巴伐利亚", "城堡", "圣诞市场"],
    gameplay_features: ["德式建筑", "圣诞市场", "啤酒馆", "欧洲小镇"]
  },
  {
    id: "tileset-kr-world-candy",
    title_en: "KR World of Candy Tileset",
    title_zh: "KR 糖果世界图块",
    category: "tileset",
    sub_category: "Fantasy/Cute",
    rating: 4.0,
    steam_rating: 83,
    price_cny: 52,
    price_cny_lowest: 42,
    steam_url: "https://store.steampowered.com/app/3998280/",
    steam_verified: true,
    steam_appid: "3998280",
    description: "甜蜜的糖果主题图块。糖果屋、巧克力河、饼干路、冰淇淋山等。色彩缤纷，适合儿童向或搞笑风格。",
    review_summary: "独特且可爱的主题。适合制作童话/子供向游戏。色彩鲜艳但不刺眼。",
    theme: "糖果/童话",
    tags: ["糖果", "可爱", "KR", "童话", "甜点", "儿童向"],
    gameplay_features: ["糖果建筑", "甜点地形", "色彩缤纷", "童话氛围"]
  },
  {
    id: "tileset-kr-vaporwave",
    title_en: "KR Vaporwave Dreams Tileset",
    title_zh: "KR 蒸汽波之梦图块",
    category: "tileset",
    sub_category: "Retro/Synthwave",
    rating: 4.2,
    steam_rating: 85,
    price_cny: 66,
    price_cny_lowest: 56,
    steam_url: "https://store.steampowered.com/app/3998300/",
    steam_verified: true,
    steam_appid: "3998300",
    description: "蒸汽波/合成波美学图块。霓虹灯、80年代风格建筑、赛博街道、复古未来主义。紫色/粉色/青色配色方案。",
    review_summary: "风格极其独特，蒸汽波美学的完美像素化。适合制作风格化独立游戏。视觉效果惊艳。",
    theme: "蒸汽波/合成波",
    tags: ["蒸汽波", "合成波", "霓虹", "80年代", "复古未来", "紫色"],
    gameplay_features: ["霓虹灯光", "赛博街道", "80年代风格", "紫色调"]
  },
  {
    id: "tileset-kr-wandering-asylum",
    title_en: "KR Wandering Souls Asylum Tileset",
    title_zh: "KR 游魂疯人院图块",
    category: "tileset",
    sub_category: "Horror/Asylum",
    rating: 4.4,
    steam_rating: 89,
    price_cny: 66,
    price_cny_lowest: 53,
    steam_url: "https://store.steampowered.com/app/3243200/",
    steam_verified: true,
    steam_appid: "3243200",
    description: "恐怖主题的精神病院图块。破败走廊、铁栅栏、手术室、阴暗病房等。氛围压抑，适合恐怖/悬疑RPG。",
    review_summary: "恐怖RPG的绝佳素材。场景设计极具压迫感。细节阴暗但不失可读性。",
    theme: "恐怖/精神病院",
    tags: ["恐怖", "精神病院", "KR", "阴暗", "悬疑", "哥特"],
    gameplay_features: ["阴暗走廊", "手术室", "铁栅栏", "破败氛围", "悬疑场景"]
  },
  {
    id: "tileset-kr-solar-base",
    title_en: "KR Solar Base Tileset",
    title_zh: "KR 太阳基地图块",
    category: "tileset",
    sub_category: "Sci-Fi/Base",
    rating: 4.0,
    steam_rating: 82,
    price_cny: 62,
    price_cny_lowest: 50,
    steam_url: "https://store.steampowered.com/app/4085300/",
    steam_verified: true,
    steam_appid: "4085300",
    description: "太空太阳能基地图块。科技感十足的室内场景、控制室、实验室、太阳能板阵列等。",
    review_summary: "科幻基地标配。科技氛围好，适合制作空间站/基地探索RPG。",
    theme: "科幻/太空基地",
    tags: ["太阳能", "基地", "KR", "太空", "科技", "实验室"],
    gameplay_features: ["控制室", "实验室", "太阳能板", "太空舱", "科技感"]
  },
  {
    id: "tileset-kr-vintage-train",
    title_en: "KR Vintage Steam Train Tileset",
    title_zh: "KR 复古蒸汽火车图块",
    category: "tileset",
    sub_category: "Steampunk/Train",
    rating: 4.2,
    steam_rating: 86,
    price_cny: 52,
    price_cny_lowest: 42,
    steam_url: "https://store.steampowered.com/app/3903380/",
    steam_verified: true,
    steam_appid: "3903380",
    description: "复古蒸汽火车主题图块。老式蒸汽机车、豪华车厢、复古车站、行李房等。维多利亚时代铁路风情。",
    review_summary: "蒸汽朋克爱好者的好选择。复古细节到位。适合制作火车旅行冒险故事。",
    theme: "蒸汽朋克/复古火车",
    tags: ["蒸汽火车", "复古", "KR", "维多利亚", "铁路", "旅行"],
    gameplay_features: ["蒸汽机车", "豪华车厢", "复古车站", "维多利亚风格"]
  },
  {
    id: "tileset-kr-legendary-palaces",
    title_en: "KR Legendary Palaces - Yeti Tileset",
    title_zh: "KR 传奇宫殿 - 雪人图块",
    category: "tileset",
    sub_category: "Fantasy/Ice",
    rating: 4.3,
    steam_rating: 87,
    price_cny: 66,
    price_cny_lowest: 53,
    steam_url: "https://store.steampowered.com/app/3364420/",
    steam_verified: true,
    steam_appid: "3364420",
    description: "冰雪主题的传奇宫殿。冰冻城堡、寒冰洞穴、动画冰晶宝石、冰冻宝箱等。完整的冰雪世界素材。",
    review_summary: "冰雪主题的精品。动画冰晶效果出色。适合制作极地/冰原冒险RPG。",
    theme: "冰雪/极地",
    tags: ["冰雪", "宫殿", "KR", "极地", "冰冻", "冒险"],
    gameplay_features: ["冰冻城堡", "动画冰晶", "寒冰洞穴", "冰冻宝箱", "极地氛围"]
  },
  {
    id: "tileset-winlu-ship",
    title_en: "Winlu Fantasy Tileset - Ship",
    title_zh: "Winlu 奇幻图块 - 船只",
    category: "tileset",
    sub_category: "Fantasy/Ship",
    rating: 4.3,
    steam_rating: 87,
    price_cny: 76,
    price_cny_lowest: 61,
    steam_url: "https://store.steampowered.com/app/4623430/",
    steam_verified: true,
    steam_appid: "4623430",
    description: "奇幻风格船只图块。完整的帆船外部/内部、视差海洋效果、动画船帆/炮台。附赠幽灵船变体版本。",
    review_summary: "海战/航海游戏必备。船只细节丰富，幽灵船变体创意十足。动画效果流畅。",
    theme: "航海/海盗",
    tags: ["船", "航海", "海盗", "Winlu", "海洋", "幽灵船"],
    gameplay_features: ["帆船甲板", "船舱内部", "海洋视差", "动画船帆", "幽灵船变体"]
  },
  {
    id: "tileset-fantasy-dreamland",
    title_en: "Fantasy Dreamland - Enchanted Pack",
    title_zh: "奇幻梦境 - 魔法包",
    category: "tileset",
    sub_category: "Fantasy/Mushroom",
    rating: 4.1,
    steam_rating: 84,
    price_cny: 30,
    price_cny_lowest: 24,
    steam_url: "https://store.steampowered.com/app/4894350/",
    steam_verified: true,
    steam_appid: "4894350",
    description: "蘑菇森林奇幻图块。巨型蘑菇、魔法植物、精灵村庄、发光孢子等。梦幻童话风格。含行走角色和SV战斗者。",
    review_summary: "小而美的主题包。蘑菇森林主题独特可爱。价格合理，性价比不错。",
    theme: "奇幻/蘑菇森林",
    tags: ["蘑菇", "魔法", "精灵", "童话", "森林", "梦幻"],
    gameplay_features: ["蘑菇建筑", "魔法植物", "发光孢子", "精灵村庄", "行走角色"]
  },
  {
    id: "tileset-serialgames-city",
    title_en: "SERIALGAMES Living Good City Tileset",
    title_zh: "SERIALGAMES 美好生活城市图块",
    category: "tileset",
    sub_category: "Modern/City",
    rating: 4.2,
    steam_rating: 86,
    price_cny: 68,
    price_cny_lowest: 31,
    steam_url: "https://store.steampowered.com/app/2286653/",
    steam_verified: true,
    steam_appid: "2286653",
    description: "现代城市生活图块。街道、商店、公寓、公园、咖啡店等日常生活场景。清新明亮的现代风格。",
    review_summary: "现代背景RPG的优质选择。城市素材丰富，日常生活感强。史低折扣力度大。",
    theme: "现代/城市",
    tags: ["现代", "城市", "街道", "商店", "日常", "SERIALGAMES"],
    gameplay_features: ["城市街道", "商店内部", "公寓", "公园", "咖啡店"]
  },
  {
    id: "tileset-grid-map",
    title_en: "Grid Map Tiles RPG Maker Edition",
    title_zh: "网格地图图块 RPG Maker版",
    category: "tileset",
    sub_category: "Dungeon/Grid",
    rating: 3.8,
    steam_rating: 80,
    price_cny: 116,
    price_cny_lowest: 52,
    steam_url: "https://store.steampowered.com/app/1967140/",
    steam_verified: true,
    steam_appid: "1967140",
    description: "类似桌游/TRPG风格的网格地图图块。地牢爬行风格，适合制作迷宫探索类RPG。网格清晰，战术感强。",
    review_summary: "桌游风格独特。价格偏高但打折时值得入手。适合DRPG/迷宫爬行类游戏。",
    theme: "桌游/地牢",
    tags: ["网格", "地牢", "桌游", "TRPG", "迷宫", "探索"],
    gameplay_features: ["网格地图", "地牢生成", "迷宫探索", "桌游风格"]
  },
  {
    id: "tileset-cn-style-tileset",
    title_en: "CN-STYLE Tileset Collection",
    title_zh: "中国风图块合集",
    category: "tileset",
    sub_category: "Asian/Chinese",
    rating: 4.5,
    steam_rating: 90,
    price_cny: 98,
    price_cny_lowest: 78,
    steam_url: "https://store.steampowered.com/app/4894310/",
    steam_verified: true,
    steam_appid: "4894310",
    description: "高质量中国风图块素材。包含古代宫殿、江湖客栈、深山寺庙、竹林小径、中式园林等。适用于武侠/仙侠题材RPG。",
    review_summary: "制作中国风RPG的首选DLC。文化还原准确，素材体量大。适合武侠、仙侠、神话题材。",
    theme: "中国风/武侠",
    tags: ["中国风", "武侠", "仙侠", "古装", "宫殿", "竹林", "寺庙"],
    gameplay_features: ["宫殿建筑", "江湖场景", "中式园林", "竹林", "寺庙"]
  },
  {
    id: "tileset-useful-laboratory",
    title_en: "Useful Laboratory Tiles",
    title_zh: "实用实验室图块",
    category: "tileset",
    sub_category: "Sci-Fi/Lab",
    rating: 4.0,
    steam_rating: 83,
    price_cny: 48,
    price_cny_lowest: 38,
    steam_url: "https://store.steampowered.com/app/4789600/",
    steam_verified: true,
    steam_appid: "4789600",
    description: "实验室主题图块。机械设备、胶囊舱、烧瓶试管、电脑终端等。适合科幻/研究设施场景。",
    review_summary: "实验室场景专用素材。细节丰富，科技感强。适合科幻RPG的关键场景。",
    theme: "科幻/实验室",
    tags: ["实验室", "机械", "科学", "胶囊", "研究", "科技"],
    gameplay_features: ["实验室设备", "胶囊舱", "电脑终端", "实验器材"]
  },
  {
    id: "tileset-kawaii-retro",
    title_en: "100% Kawaii Retro Tilesets",
    title_zh: "100%可爱复古图块",
    category: "tileset",
    sub_category: "Retro/Pixel",
    rating: 4.2,
    steam_rating: 85,
    price_cny: 56,
    price_cny_lowest: 45,
    steam_url: "https://store.steampowered.com/app/4789560/",
    steam_verified: true,
    steam_appid: "4789560",
    description: "明亮可爱的复古像素风格图块。户外场景为主，包括鸟居、神社、日本风格建筑和自然景观。色彩鲜艳的像素艺术。",
    review_summary: "日本复古风格，可爱且独特。像素艺术品质高。适合制作日式冒险RPG。",
    theme: "日式/复古",
    tags: ["可爱", "复古", "像素", "日式", "鸟居", "Kawaii"],
    gameplay_features: ["日式建筑", "鸟居", "神社", "像素风格", "明亮色调"]
  },
  {
    id: "tileset-kim-lighting",
    title_en: "KIM Lighting Tileset",
    title_zh: "KIM 光照图块",
    category: "tileset",
    sub_category: "Visual/Lighting",
    rating: 4.3,
    steam_rating: 86,
    price_cny: 36,
    price_cny_lowest: 29,
    steam_url: "https://store.steampowered.com/app/4961490/",
    steam_verified: true,
    steam_appid: "4961490",
    description: "光照效果图块素材。预设的光线投射、灯光、窗户光、火把光等覆盖层。用于增强地图的光影氛围。",
    review_summary: "实用的光影增强素材。与任何图块配合使用。简单但效果显著。价格亲民。",
    theme: "光照/氛围",
    tags: ["光照", "光影", "覆盖层", "氛围", "灯光", "窗户光"],
    gameplay_features: ["光线覆盖层", "灯光效果", "窗户光", "火把光", "氛围增强"]
  },
  {
    id: "tileset-topdown-legends",
    title_en: "Topdown Legends Graphic Pack - Towns and Forests",
    title_zh: "俯视传说图形包 - 城镇与森林",
    category: "tileset",
    sub_category: "Fantasy/Topdown",
    rating: 4.1,
    steam_rating: 84,
    price_cny: 30,
    price_cny_lowest: 24,
    steam_url: "https://store.steampowered.com/app/4961500/",
    steam_verified: true,
    steam_appid: "4961500",
    description: "俯视视角的城镇和森林图形素材。适合2D俯视RPG风格。城镇建筑和自然景观的完整套装。",
    review_summary: "俯视视角的优质素材。价格实惠。与默认RTP风格兼容性好。",
    theme: "俯视/奇幻",
    tags: ["俯视", "城镇", "森林", "Topdown", "2D", "自然"],
    gameplay_features: ["俯视视角", "城镇建筑", "森林景观", "自然元素"]
  },
  {
    id: "tileset-essentials",
    title_en: "Essentials Set",
    title_zh: "基础套装",
    category: "tileset",
    sub_category: "Fantasy/Basic",
    rating: 3.8,
    steam_rating: 78,
    price_cny: 40,
    price_cny_lowest: 20,
    steam_url: "https://store.steampowered.com/app/1350880/",
    steam_verified: true,
    steam_appid: "1350880",
    description: "MZ基础素材补充包。包含常用的图块、音效和角色素材。适合新手入门和快速原型开发。",
    review_summary: "入门级素材包。内容基础但实用。对新手友好，老手可能觉得内容不够丰富。",
    theme: "通用/基础",
    tags: ["基础", "入门", "通用", "补充", "新手"],
    gameplay_features: ["基础图块", "常用音效", "角色补充"]
  },
  {
    id: "tileset-time-animals",
    title_en: "Time Fantasy Add-on: Animals",
    title_zh: "时间幻想附加: 动物",
    category: "tileset",
    sub_category: "Retro/Animals",
    rating: 4.0,
    steam_rating: 82,
    price_cny: 10,
    price_cny_lowest: 7,
    steam_url: "https://store.steampowered.com/app/1441940/",
    steam_verified: true,
    steam_appid: "1441940",
    description: "Time Fantasy风格的动物角色附加包。小巧可爱的像素风格动物素材。可配合Time Fantasy系列使用。",
    review_summary: "价格极低的小附加包。Time Fantasy系列的补充。动物种类实用。",
    theme: "像素/动物",
    tags: ["像素", "动物", "Time Fantasy", "附加", "可爱"],
    gameplay_features: ["动物行走图", "像素风格", "小动物"]
  },

  // ============================================================
  // 🎵 MUSIC / 音乐包
  // ============================================================
  {
    id: "music-blossom",
    title_en: "Blossom Music Pack",
    title_zh: "绽放音乐包",
    category: "music",
    sub_category: "Orchestral/Fantasy",
    rating: 4.3,
    steam_rating: 88,
    price_cny: 98,
    price_cny_lowest: 78,
    steam_url: "https://store.steampowered.com/app/4894320/",
    steam_verified: true,
    steam_appid: "4894320",
    description: "20首BGM + 10首ME的高质量音乐包。管弦乐风格，适合RPG和悬疑游戏。旋律优美，制作精良。",
    review_summary: "管弦乐品质出色。曲风多样，从轻快到史诗都有覆盖。适合正统奇幻RPG。",
    theme: "管弦/奇幻",
    tags: ["管弦乐", "BGM", "奇幻", "史诗", "旋律", "悬疑"],
    gameplay_features: ["20首BGM", "10首ME", "管弦编曲", "多样曲风"]
  },
  {
    id: "music-nightwalker",
    title_en: "Nightwalker Music Pack",
    title_zh: "夜行者音乐包",
    category: "music",
    sub_category: "Modern/Urban",
    rating: 4.4,
    steam_rating: 90,
    price_cny: 124,
    price_cny_lowest: 99,
    steam_url: "https://store.steampowered.com/app/4894330/",
    steam_verified: true,
    steam_appid: "4894330",
    description: "21首BGM + 11首ME的现代都市夜晚主题音乐包。都市夜生活、霓虹街头、神秘氛围。融合电子和爵士元素。",
    review_summary: "现代都市风格音乐的精品。氛围感极强，适合现代/赛博朋克背景RPG。制作水准高。",
    theme: "都市/夜晚",
    tags: ["都市", "夜晚", "电子", "爵士", "现代", "霓虹"],
    gameplay_features: ["21首BGM", "11首ME", "电子爵士", "都市氛围"]
  },
  {
    id: "music-neon-frostwave",
    title_en: "Neon Frostwave Music Pack",
    title_zh: "霓虹霜波音乐包",
    category: "music",
    sub_category: "Retro/Synth",
    rating: 4.2,
    steam_rating: 86,
    price_cny: 48,
    price_cny_lowest: 38,
    steam_url: "https://store.steampowered.com/app/4744480/",
    steam_verified: true,
    steam_appid: "4744480",
    description: "6首复古科幻/悬疑/恐怖风格的合成器音乐。受1970-80年代媒体启发。合成波和电子音乐的结合。",
    review_summary: "独特的老派合成器风格。量少但质量高。适合复古科幻和悬疑题材。",
    theme: "合成器/复古",
    tags: ["合成器", "复古", "科幻", "80年代", "电子", "悬疑"],
    gameplay_features: ["6首BGM", "合成器音色", "复古科幻", "悬疑氛围"]
  },
  {
    id: "music-echoes-broken",
    title_en: "Echoes of a Broken World",
    title_zh: "破碎世界的回响",
    category: "music",
    sub_category: "Story-driven/Emotional",
    rating: 4.5,
    steam_rating: 91,
    price_cny: 88,
    price_cny_lowest: 70,
    steam_url: "https://store.steampowered.com/app/4651390/",
    steam_verified: true,
    steam_appid: "4651390",
    description: "23首沉浸式叙事向音乐。适合故事驱动的RPG。情感丰富，从悲伤到希望的情绪跨度。管弦乐与钢琴为主。",
    review_summary: "最富情感表达的音乐包之一。叙事向RPG的完美配乐。适合重剧情的游戏。",
    theme: "叙事/情感",
    tags: ["叙事", "情感", "钢琴", "管弦", "沉浸", "剧情"],
    gameplay_features: ["23首BGM", "管弦钢琴", "情感表达", "叙事驱动"]
  },
  {
    id: "music-celtic-albion",
    title_en: "ECHOES OF ALBION: A Celtic RPG Music Pack",
    title_zh: "阿尔比恩的回响: 凯尔特RPG音乐包",
    category: "music",
    sub_category: "Celtic/Folk",
    rating: 4.3,
    steam_rating: 88,
    price_cny: 66,
    price_cny_lowest: 53,
    steam_url: "https://store.steampowered.com/app/4651420/",
    steam_verified: true,
    steam_appid: "4651420",
    description: "10首凯尔特风格音乐。小提琴、爱尔兰哨笛、竖琴等传统乐器。充满凯尔特神话和欧洲中世纪的氛围。",
    review_summary: "凯尔特风格音乐的上乘之作。传统乐器演奏出色。适合中世纪欧洲背景RPG。",
    theme: "凯尔特/中世纪",
    tags: ["凯尔特", "中世纪", "小提琴", "哨笛", "竖琴", "欧洲"],
    gameplay_features: ["10首BGM", "传统乐器", "凯尔特风格", "中世纪氛围"]
  },
  {
    id: "music-retro-horror",
    title_en: "Pandora's Puppet: Retro Horror Music Pack",
    title_zh: "潘多拉人偶: 复古恐怖音乐包",
    category: "music",
    sub_category: "Horror/Synth",
    rating: 4.1,
    steam_rating: 84,
    price_cny: 48,
    price_cny_lowest: 38,
    steam_url: "https://store.steampowered.com/app/4789590/",
    steam_verified: true,
    steam_appid: "4789590",
    description: "6首大气合成器恐怖音乐。受经典恐怖片配乐启发。压抑、不安的声景，适合恐怖RPG。",
    review_summary: "恐怖游戏配乐的精品。量少但每首质量高。合成器音色的恐怖感非常到位。",
    theme: "恐怖/合成器",
    tags: ["恐怖", "合成器", "复古", "压抑", "恐惧", "氛围"],
    gameplay_features: ["6首BGM", "恐怖氛围", "合成器音景", "压抑感"]
  },
  {
    id: "music-realization",
    title_en: "Realization Music Pack",
    title_zh: "觉醒音乐包",
    category: "music",
    sub_category: "Orchestral/Epic",
    rating: 4.2,
    steam_rating: 85,
    price_cny: 98,
    price_cny_lowest: 78,
    steam_url: "https://store.steampowered.com/app/4961520/",
    steam_verified: true,
    steam_appid: "4961520",
    description: "管弦史诗风格音乐包。宏大的冒险主题，适合JRPG和英雄旅程故事。情感张力强。",
    review_summary: "史诗感音乐包。管弦编曲宏大。适合主打宏大叙事的RPG。",
    theme: "史诗/管弦",
    tags: ["史诗", "管弦", "冒险", "JRPG", "宏大", "英雄"],
    gameplay_features: ["管弦编曲", "史诗冒险", "JRPG风格", "宏大叙事"]
  },
  {
    id: "music-hearthlight-vale",
    title_en: "Hearthlight Vale Cozy Music Pack",
    title_zh: "炉光谷温馨音乐包",
    category: "music",
    sub_category: "Cozy/Fantasy",
    rating: 4.3,
    steam_rating: 87,
    price_cny: 50,
    price_cny_lowest: 40,
    steam_url: "https://store.steampowered.com/app/4961480/",
    steam_verified: true,
    steam_appid: "4961480",
    description: "温馨舒适的奇幻音乐。柔和旋律，适合村庄、旅店、田园场景。治愈系音乐风格。",
    review_summary: "治愈系RPG的完美配乐。温馨但不幼稚。适合生活模拟/休闲RPG。",
    theme: "温馨/治愈",
    tags: ["温馨", "治愈", "村庄", "田园", "舒适", "柔和"],
    gameplay_features: ["柔和旋律", "田园氛围", "治愈风格", "村庄BGM"]
  },
  {
    id: "music-dark-game",
    title_en: "Dark Game Music Asset Pack",
    title_zh: "黑暗游戏音乐素材包",
    category: "music",
    sub_category: "Dark/Horror",
    rating: 4.0,
    steam_rating: 82,
    price_cny: 76,
    price_cny_lowest: 61,
    steam_url: "https://store.steampowered.com/app/3950580/",
    steam_verified: true,
    steam_appid: "3950580",
    description: "黑暗风格游戏音乐包。压抑的氛围音乐、紧张的战斗曲、诡异的探索曲。适合恐怖/暗黑奇幻RPG。",
    review_summary: "暗黑风格音乐的质量之选。恐怖和紧张氛围到位。适合恐怖/暗黑题材。",
    theme: "黑暗/恐怖",
    tags: ["黑暗", "恐怖", "紧张", "诡异", "暗黑奇幻", "氛围"],
    gameplay_features: ["暗黑氛围", "紧张战斗曲", "恐怖探索", "诡异音效"]
  },
  {
    id: "music-versatile-jrpg",
    title_en: "Versatile JRPG Music Pack",
    title_zh: "多用途JRPG音乐包",
    category: "music",
    sub_category: "JRPG/Orchestral",
    rating: 4.3,
    steam_rating: 88,
    price_cny: 52,
    price_cny_lowest: 31,
    steam_url: "https://store.steampowered.com/app/2634580/",
    steam_verified: true,
    steam_appid: "2634580",
    description: "多场景适用的JRPG风格音乐包。涵盖战斗、城镇、迷宫、事件等场景。管弦乐和摇滚元素混合。",
    review_summary: "实用且全面的JRPG音乐包。质量稳定，场景覆盖广。价格合理，打折时性价比极高。",
    theme: "JRPG/综合",
    tags: ["JRPG", "管弦", "战斗", "城镇", "综合", "日式"],
    gameplay_features: ["战斗BGM", "城镇BGM", "迷宫BGM", "事件BGM", "管弦摇滚"]
  },
  {
    id: "music-8bit-happy",
    title_en: "8bit Happy Vibes",
    title_zh: "8bit快乐律动",
    category: "music",
    sub_category: "Chiptune/8bit",
    rating: 4.1,
    steam_rating: 84,
    price_cny: 66,
    price_cny_lowest: 46,
    steam_url: "https://store.steampowered.com/app/3773250/",
    steam_verified: true,
    steam_appid: "3773250",
    description: "欢快的8bit/Chiptune风格音乐。复古游戏机音色，活泼向上的旋律。适合像素风格/复古RPG。",
    review_summary: "8bit爱好者的快乐源泉。旋律抓耳，复古感十足。适合轻松愉快的像素RPG。",
    theme: "8bit/复古",
    tags: ["8bit", "复古", "欢快", "像素", "Chiptune", "FC风格"],
    gameplay_features: ["8bit音色", "欢快旋律", "复古游戏风格", "活泼节奏"]
  },
  {
    id: "music-ultimate-saga-2",
    title_en: "ULTIMATE RPG SAGA MUSIC DLC 2",
    title_zh: "终极RPG传奇音乐DLC 2",
    category: "music",
    sub_category: "Epic/Orchestral",
    rating: 4.2,
    steam_rating: 86,
    price_cny: 52,
    price_cny_lowest: 36,
    steam_url: "https://store.steampowered.com/app/3857480/",
    steam_verified: true,
    steam_appid: "3857480",
    description: "终极RPG传奇系列第二弹。史诗管弦乐，宏大的冒险配乐。适合大型RPG项目。",
    review_summary: "系列第二作，品质延续。史诗感强，适合大型项目。价格合理。",
    theme: "史诗/管弦",
    tags: ["史诗", "管弦", "传奇", "宏大", "冒险", "大型项目"],
    gameplay_features: ["史诗管弦", "冒险BGM", "战斗音乐", "宏大叙事"]
  },
  {
    id: "music-fantasy-wonderland",
    title_en: "Fantasy Wonderland RPG Music",
    title_zh: "奇幻仙境RPG音乐",
    category: "music",
    sub_category: "Fantasy/Whimsical",
    rating: 4.0,
    steam_rating: 82,
    price_cny: 56,
    price_cny_lowest: 45,
    steam_url: "https://store.steampowered.com/app/3364410/",
    steam_verified: true,
    steam_appid: "3364410",
    description: "10首奇幻仙境风格BGM，含主题旋律变奏。梦幻、奇妙的音乐氛围。适合童话/梦幻RPG。",
    review_summary: "梦幻风格音乐。旋律变奏设计巧妙。适合童话类/轻松奇幻RPG。",
    theme: "梦幻/童话",
    tags: ["奇幻", "仙境", "梦幻", "童话", "变奏", "奇妙"],
    gameplay_features: ["10首BGM", "旋律变奏", "梦幻氛围", "童话风格"]
  },
  {
    id: "music-dark-dungeon",
    title_en: "Dark Dungeon: Background Music",
    title_zh: "黑暗地牢: 背景音乐",
    category: "music",
    sub_category: "Dark/Dungeon",
    rating: 3.9,
    steam_rating: 80,
    price_cny: 46,
    price_cny_lowest: 37,
    steam_url: "https://store.steampowered.com/app/4513440/",
    steam_verified: true,
    steam_appid: "4513440",
    description: "7首黑暗地下城氛围音乐。低沉、压抑的地牢探索配乐。适合地下城/迷宫场景。",
    review_summary: "地牢场景专用。氛围到位。曲子数量少但每首质量过关。",
    theme: "地牢/黑暗",
    tags: ["地牢", "黑暗", "地下城", "压抑", "探索", "氛围"],
    gameplay_features: ["7首BGM", "地牢氛围", "低沉音调", "探索配乐"]
  },
  {
    id: "music-battle-dungeon-anthems",
    title_en: "Battle and Dungeon Anthems Vol02",
    title_zh: "战斗与地牢圣歌 Vol.02",
    category: "music",
    sub_category: "Battle/Rock",
    rating: 4.2,
    steam_rating: 85,
    price_cny: 66,
    price_cny_lowest: 53,
    steam_url: "https://store.steampowered.com/app/4112850/",
    steam_verified: true,
    steam_appid: "4112850",
    description: "10首管弦摇滚风格战斗曲。激昂的战斗音乐和紧张的地牢探索曲。适合动作感强的RPG。",
    review_summary: "战斗音乐的高质量选择。管弦摇滚融合出色。适合需要激烈战斗BGM的游戏。",
    theme: "战斗/摇滚",
    tags: ["战斗", "摇滚", "管弦", "激昂", "地牢", "激烈"],
    gameplay_features: ["10首BGM", "管弦摇滚", "战斗曲", "地牢曲"]
  },
  {
    id: "music-harmonic-realms-2",
    title_en: "Ben Carter - Harmonic Realms II",
    title_zh: "Ben Carter - 和声领域 II",
    category: "music",
    sub_category: "Dark/Mysterious",
    rating: 4.3,
    steam_rating: 87,
    price_cny: 66,
    price_cny_lowest: 53,
    steam_url: "https://store.steampowered.com/app/4112870/",
    steam_verified: true,
    steam_appid: "4112870",
    description: "17首黑暗/神秘风格BGM + 5首SFX/ME。Ben Carter系列第二作。深沉神秘的音乐氛围。",
    review_summary: "Ben Carter系列品质稳定。暗黑神秘风格出色。适合悬疑/神秘题材RPG。",
    theme: "黑暗/神秘",
    tags: ["黑暗", "神秘", "Ben Carter", "悬疑", "深沉", "氛围"],
    gameplay_features: ["17首BGM", "5首SFX", "黑暗氛围", "神秘风格"]
  },
  {
    id: "music-depths-dungeon",
    title_en: "Depths of the World - Depths Dungeon Sound Pack",
    title_zh: "世界深处 - 深渊地牢音效包",
    category: "music",
    sub_category: "Epic/Dungeon",
    rating: 4.1,
    steam_rating: 84,
    price_cny: 48,
    price_cny_lowest: 38,
    steam_url: "https://store.steampowered.com/app/4320000/RPG_Maker_MZ__Depths_of_the_World_Depths_Dungeon_Sound_Pack/",
    steam_verified: false,
    steam_appid: "4320000",
    description: "12首史诗/神秘风格曲目，含37种变奏版本。地牢深处的宏大音乐体验。",
    review_summary: "变奏版本丰富，适应性好。地牢主题音乐的上乘之选。",
    theme: "史诗/地牢",
    tags: ["地牢", "史诗", "神秘", "深度", "变奏", "宏大"],
    gameplay_features: ["12首+37变奏", "地牢主题", "史诗风格", "多版本"]
  },

  // ============================================================
  // 🔊 SFX / 音效包
  // ============================================================
  {
    id: "sfx-analog-utility",
    title_en: "Analog Utility Sounds",
    title_zh: "模拟实用音效",
    category: "sfx",
    sub_category: "General/UI",
    rating: 4.0,
    steam_rating: 83,
    price_cny: 48,
    price_cny_lowest: 38,
    steam_url: "https://store.steampowered.com/app/3495930/",
    steam_verified: true,
    steam_appid: "3495930",
    description: "200个通用音效。涵盖UI、菜单、确认、取消、提示等常用音效。模拟质感，实用性强。",
    review_summary: "量大实用的通用音效包。UI音效尤其好用。适合任何类型RPG的基础音效需求。",
    theme: "通用/UI",
    tags: ["音效", "UI", "通用", "模拟", "菜单", "提示"],
    gameplay_features: ["200个音效", "UI音效", "菜单音效", "提示音", "确认音"]
  },
  {
    id: "sfx-addon-rm2k",
    title_en: "Add-on Vol.1: RM2k Rearrange Soundtrack & SE",
    title_zh: "附加包 Vol.1: RM2k 重编曲与原声SE",
    category: "sfx",
    sub_category: "Retro/Classic",
    rating: 4.4,
    steam_rating: 90,
    price_cny: 48,
    price_cny_lowest: 24,
    steam_url: "https://store.steampowered.com/app/1350900/",
    steam_verified: true,
    steam_appid: "1350900",
    description: "经典RPG Maker 2000原声的重新编排版本。怀旧的BGM和音效，经过现代混音处理。老玩家必入的情怀之作。",
    review_summary: "情怀满分！RM2k经典曲目的高质量重编。老玩家泪目系列。新玩家也能欣赏其音乐品质。",
    theme: "怀旧/经典",
    tags: ["RM2k", "经典", "怀旧", "重编曲", "情怀", "复古"],
    gameplay_features: ["RM2k原声", "重编曲", "经典BGM", "怀旧音效"]
  },
  {
    id: "sfx-status-icon",
    title_en: "Status Icon & OtherWorld Music Set",
    title_zh: "状态图标与异世界音乐套装",
    category: "sfx",
    sub_category: "Dark/Status",
    rating: 3.9,
    steam_rating: 80,
    price_cny: 56,
    price_cny_lowest: 45,
    steam_url: "https://store.steampowered.com/app/3495960/",
    steam_verified: true,
    steam_appid: "3495960",
    description: "23个状态图标素材和暗黑世界风格音乐/音效。适合暗黑异世界题材RPG。",
    review_summary: "图标与音效的混合包。暗黑风格统一。适合特定题材。",
    theme: "暗黑/异世界",
    tags: ["音效", "图标", "暗黑", "异世界", "状态", "氛围"],
    gameplay_features: ["23个状态图标", "暗黑音乐", "异世界氛围", "状态音效"]
  },

  // ============================================================
  // 👤 CHARACTER / 角色素材
  // ============================================================
  {
    id: "char-hero-generator",
    title_en: "Hero Character Generator for MZ",
    title_zh: "英雄角色生成器 for MZ",
    category: "character",
    sub_category: "Generator Parts",
    rating: 4.3,
    steam_rating: 87,
    price_cny: 66,
    price_cny_lowest: 53,
    steam_url: "https://store.steampowered.com/app/3364430/",
    steam_verified: true,
    steam_appid: "3364430",
    description: "57种男性角色生成器部件。包含武士、赛博格、太空游侠、吸血鬼王子等多种英雄类型。",
    review_summary: "男性角色部件的优质补充。类型多样，科幻和奇幻兼顾。品质上乘。",
    theme: "英雄/多样化",
    tags: ["角色生成器", "英雄", "男性", "武士", "赛博格", "吸血鬼"],
    gameplay_features: ["57种部件", "多类型英雄", "生成器兼容", "男性角色"]
  },
  {
    id: "char-traditional-chinese",
    title_en: "Traditional Chinese Character Generator",
    title_zh: "中国传统角色生成器",
    category: "character",
    sub_category: "Generator Parts",
    rating: 4.4,
    steam_rating: 89,
    price_cny: 66,
    price_cny_lowest: 53,
    steam_url: "https://store.steampowered.com/app/4603310/",
    steam_verified: true,
    steam_appid: "4603310",
    description: "中国风角色生成器部件。包含武侠、道士、商人、书生等传统中国角色类型。古装服饰和发型。",
    review_summary: "中国风RPG的绝佳搭配。角色类型丰富，文化元素准确。制作武侠/仙侠游戏的必备。",
    theme: "中国风/古装",
    tags: ["中国风", "武侠", "道士", "古装", "角色生成器", "传统"],
    gameplay_features: ["中国风部件", "武侠角色", "古装服饰", "传统发型"]
  },
  {
    id: "char-kids-generator",
    title_en: "Kids Character Generator",
    title_zh: "儿童角色生成器",
    category: "character",
    sub_category: "Generator Parts",
    rating: 4.1,
    steam_rating: 84,
    price_cny: 56,
    price_cny_lowest: 45,
    steam_url: "https://store.steampowered.com/app/4559580/",
    steam_verified: true,
    steam_appid: "4559580",
    description: "儿童角色生成器部件。包括王子、公主等儿童角色选项。可爱的儿童比例和服装。",
    review_summary: "儿童角色素材的稀缺品。可爱且实用。适合有儿童角色的RPG。",
    theme: "儿童/可爱",
    tags: ["儿童", "孩子", "王子", "公主", "可爱", "生成器"],
    gameplay_features: ["儿童比例", "王子公主", "可爱服装", "儿童发型"]
  },
  {
    id: "char-another-world-heroine-8",
    title_en: "Another World Heroine Generator 8 for MZ",
    title_zh: "异世界女主角生成器 8 for MZ",
    category: "character",
    sub_category: "Generator Parts",
    rating: 4.2,
    steam_rating: 86,
    price_cny: 66,
    price_cny_lowest: 53,
    steam_url: "https://store.steampowered.com/app/4623440/",
    steam_verified: true,
    steam_appid: "4623440",
    description: "第8弹女主角生成器！40种武士主题的女性角色生成器部件。和风盔甲、武器、发型等。",
    review_summary: "系列第8作，品质保持。武士/和风主题独特。女性角色选择更加丰富。",
    theme: "和风/武士",
    tags: ["女主角", "武士", "和风", "女性", "生成器", "日式"],
    gameplay_features: ["40种部件", "武士主题", "和风盔甲", "女性角色"]
  },
  {
    id: "char-fantasy-generator-knight",
    title_en: "Fantasy Generator 2 Knight Armor Part Set",
    title_zh: "奇幻生成器2 骑士盔甲部件套装",
    category: "character",
    sub_category: "Generator Parts",
    rating: 4.0,
    steam_rating: 82,
    price_cny: 66,
    price_cny_lowest: 53,
    steam_url: "https://store.steampowered.com/app/4961510/",
    steam_verified: true,
    steam_appid: "4961510",
    description: "骑士盔甲主题的角色生成器部件。包含各种风格的骑士头盔、铠甲、盾牌、披风等。",
    review_summary: "骑士/中世纪风格的优质部件。盔甲设计精细。适合中世纪奇幻RPG。",
    theme: "骑士/中世纪",
    tags: ["骑士", "盔甲", "中世纪", "奇幻", "生成器", "铠甲"],
    gameplay_features: ["骑士头盔", "铠甲部件", "盾牌", "披风", "中世纪风格"]
  },
  {
    id: "char-male-generator",
    title_en: "Male Character Generator",
    title_zh: "男性角色生成器",
    category: "character",
    sub_category: "Generator Parts",
    rating: 4.0,
    steam_rating: 82,
    price_cny: 56,
    price_cny_lowest: 45,
    steam_url: "https://store.steampowered.com/app/4651410/",
    steam_verified: true,
    steam_appid: "4651410",
    description: "奇幻职业男性角色生成器部件。战士、法师、盗贼、猎人等经典奇幻职业造型。",
    review_summary: "经典奇幻职业角色的补充包。职业特色鲜明。基础但实用。",
    theme: "奇幻/职业",
    tags: ["男性", "奇幻职业", "战士", "法师", "生成器", "经典"],
    gameplay_features: ["职业造型", "战士部件", "法师部件", "男性角色"]
  },
  {
    id: "char-mv-cover-art",
    title_en: "MV Cover Art Characters Pack",
    title_zh: "MV封面角色包",
    category: "character",
    sub_category: "Hero Set",
    rating: 4.2,
    steam_rating: 86,
    price_cny: 48,
    price_cny_lowest: 24,
    steam_url: "https://store.steampowered.com/app/1350870/",
    steam_verified: true,
    steam_appid: "1350870",
    description: "基于RPG Maker MV封面艺术的角色素材包。包含主要英雄角色的行走图、SV战斗图和面孔图。经典主角阵容。",
    review_summary: "经典封面角色的完整素材。MV版英雄在MZ中完美使用。情怀和实用兼备。",
    theme: "经典/英雄",
    tags: ["MV", "封面", "英雄", "经典", "主角", "行走图"],
    gameplay_features: ["英雄行走图", "SV战斗图", "面孔图", "经典主角"]
  },
  {
    id: "char-addon-rm2k-hero",
    title_en: "Add-on Vol.2: RM2K Hero Character Pack",
    title_zh: "附加包 Vol.2: RM2K 英雄角色包",
    category: "character",
    sub_category: "Retro/Classic",
    rating: 4.5,
    steam_rating: 92,
    price_cny: 48,
    price_cny_lowest: 24,
    steam_url: "https://store.steampowered.com/app/1350910/",
    steam_verified: true,
    steam_appid: "1350910",
    description: "经典RM2k英雄角色在MZ中的复活。以MZ规格重新绘制的经典角色行走图和战斗图。老玩家的终极情怀。",
    review_summary: "RM2k粉丝的情怀之选！经典角色高清化。老玩家社区评价极高。",
    theme: "怀旧/经典",
    tags: ["RM2k", "经典", "英雄", "怀旧", "高清", "情怀"],
    gameplay_features: ["经典角色", "高清重绘", "行走图", "战斗图", "RM2k"]
  },
  {
    id: "char-isekai-creators",
    title_en: "ISEKAI CREATORS Assets Pack",
    title_zh: "异世界创作者素材包",
    category: "character",
    sub_category: "Isekai/Generator",
    rating: 4.4,
    steam_rating: 90,
    price_cny: 138,
    price_cny_lowest: 97,
    steam_url: "https://store.steampowered.com/app/2525960/",
    steam_verified: true,
    steam_appid: "2525960",
    description: "面向异世界题材的综合素材包。包含大量角色生成器部件、图块、音乐和音效。专为异世界转生/召唤类RPG设计。",
    review_summary: "异世界题材的一站式解决方案。内容全面，品质上乘。动漫风格鲜明。史低折扣不错。",
    theme: "异世界/动漫",
    tags: ["异世界", "动漫", "转生", "综合", "生成器", "日式"],
    gameplay_features: ["生成器部件", "图块素材", "BGM", "异世界风格", "动漫角色"]
  },

  // ============================================================
  // ⚔️ BATTLER / 战斗角色
  // ============================================================
  {
    id: "battler-demon-lord-5",
    title_en: "Demon Lord Army Set 5",
    title_zh: "魔王军套装 5",
    category: "battler",
    sub_category: "Enemy/Monster",
    rating: 4.2,
    steam_rating: 86,
    price_cny: 56,
    price_cny_lowest: 45,
    steam_url: "https://store.steampowered.com/app/4651400/",
    steam_verified: true,
    steam_appid: "4651400",
    description: "52种敌人类型及变体，含面孔图。魔王军系列的第五弹。更多恶魔、怪物和BOSS级敌人。前/侧视图兼容。",
    review_summary: "魔王军系列品质稳定。敌人种类丰富。面孔图让剧情演出更生动。",
    theme: "魔王/怪物",
    tags: ["怪物", "魔王", "敌人", "BOSS", "面孔图", "战斗"],
    gameplay_features: ["52种敌人", "面孔图", "BOSS战", "前后视图兼容"]
  },
  {
    id: "battler-mega-fantasy-sv",
    title_en: "MEGA FANTASY SV Actors",
    title_zh: "MEGA 奇幻侧视战斗角色",
    category: "battler",
    sub_category: "SV Battlers",
    rating: 4.3,
    steam_rating: 88,
    price_cny: 76,
    price_cny_lowest: 61,
    steam_url: "https://store.steampowered.com/app/4789580/",
    steam_verified: true,
    steam_appid: "4789580",
    description: "大量侧视战斗角色精灵。多种职业和风格的SV战斗者。适合需要大量战斗角色的大型RPG项目。",
    review_summary: "SV战斗角色的海量补充。职业覆盖广。大型项目的性价比之选。",
    theme: "奇幻/SV",
    tags: ["SV", "侧视战斗", "角色精灵", "多种职业", "战斗"],
    gameplay_features: ["SV战斗精灵", "多职业", "大量角色", "侧视战斗"]
  },
  {
    id: "battler-ex-monster-1",
    title_en: "EX Graphic Monster Pack 1",
    title_zh: "EX图形怪物包 1",
    category: "battler",
    sub_category: "Enemy/Monster",
    rating: 4.1,
    steam_rating: 84,
    price_cny: 56,
    price_cny_lowest: 45,
    steam_url: "https://store.steampowered.com/app/3495950/",
    steam_verified: true,
    steam_appid: "3495950",
    description: "38种侧视敌人类型。精致的像素怪物设计。涵盖野兽、亡灵、元素生物等经典怪物类型。",
    review_summary: "EX系列怪物品质高。像素细节好。经典怪物类型覆盖全面。",
    theme: "怪物/像素",
    tags: ["怪物", "EX", "像素", "侧视", "敌人", "野兽"],
    gameplay_features: ["38种怪物", "侧视战斗", "像素风格", "经典怪物"]
  },
  {
    id: "battler-2way-ocean",
    title_en: "2Way-type Enemy Pack Vol2 Ocean",
    title_zh: "2Way型敌人包 Vol.2 海洋",
    category: "battler",
    sub_category: "Enemy/Ocean",
    rating: 4.0,
    steam_rating: 82,
    price_cny: 52,
    price_cny_lowest: 42,
    steam_url: "https://store.steampowered.com/app/4559570/",
    steam_verified: true,
    steam_appid: "4559570",
    description: "海洋主题怪物敌人包。海怪、鱼类怪物、水母等海洋生物敌人。前后视图均兼容。",
    review_summary: "海洋主题敌人的稀缺资源。海怪设计有创意。适合海洋/岛屿RPG。",
    theme: "海洋/怪物",
    tags: ["海洋", "海怪", "水母", "鱼类", "2Way", "船战"],
    gameplay_features: ["海洋怪物", "前后视图兼容", "海怪BOSS", "水下敌人"]
  },
  {
    id: "battler-animation-material",
    title_en: "Animation Battler Material Collection - Travel Companion Sets",
    title_zh: "动画战斗素材合集 - 旅伴套装",
    category: "battler",
    sub_category: "Animated/UNITE",
    rating: 4.2,
    steam_rating: 85,
    price_cny: 88,
    price_cny_lowest: 70,
    steam_url: "https://store.steampowered.com/app/4315000/RPG_Maker_MZ__Animation_Battler_Material_Collection/",
    steam_verified: false,
    steam_appid: "4315000",
    description: "UNITE风格的动画战斗角色素材。旅伴主题系列，包含多个旅行伙伴角色的完整战斗动画。适合动画丰富的RPG。",
    review_summary: "动画战斗角色的优质选择。UNITE风格与MZ原生风格不同但可混搭。动画流畅。",
    theme: "动画/UNITE",
    tags: ["动画", "UNITE", "战斗", "旅伴", "角色", "动态"],
    gameplay_features: ["完整战斗动画", "UNITE风格", "旅伴角色", "多套装"]
  },

  // ============================================================
  // ✨ ANIMATION / 动画特效
  // ============================================================
  {
    id: "anim-particle-3d",
    title_en: "3D Particle Effect Pack",
    title_zh: "3D粒子特效包",
    category: "animation",
    sub_category: "Particle/3D",
    rating: 4.4,
    steam_rating: 89,
    price_cny: 76,
    price_cny_lowest: 61,
    steam_url: "https://store.steampowered.com/app/1351020/",
    steam_verified: true,
    steam_appid: "1351020",
    description: "3D粒子特效素材包。火焰、冰霜、闪电、光效等现代粒子动画。视觉效果远超MZ默认特效。",
    review_summary: "战斗特效升级的利器。3D粒子效果大幅提升画面表现力。适合追求视觉效果的项目。",
    theme: "3D/粒子",
    tags: ["3D", "粒子", "特效", "火焰", "闪电", "现代"],
    gameplay_features: ["3D粒子", "火焰特效", "冰霜特效", "闪电特效", "光效"]
  },

  // ============================================================
  // 🖼️ ICON / 图标素材
  // ============================================================
  {
    id: "icon-listhobi-library",
    title_en: "Listhobi's Library",
    title_zh: "Listhobi的图书馆",
    category: "icon",
    sub_category: "Book/Scroll",
    rating: 4.1,
    steam_rating: 84,
    price_cny: 36,
    price_cny_lowest: 29,
    steam_url: "https://store.steampowered.com/app/3495920/",
    steam_verified: true,
    steam_appid: "3495920",
    description: "517个书籍/卷轴/石板主题图标。涵盖各种类型的书籍图标：魔法书、古卷、羊皮纸、石板等。数量惊人。",
    review_summary: "书籍主题图标的终极合集。517个图标数量惊人。适合需要大量物品图标的RPG。",
    theme: "书籍/知识",
    tags: ["图标", "书籍", "卷轴", "魔法书", "物品", "大量"],
    gameplay_features: ["517个图标", "书籍主题", "魔法书", "古卷", "物品图标"]
  },

  // ============================================================
  // 📦 BUNDLES / 捆绑包
  // ============================================================
  {
    id: "bundle-autumn-2025",
    title_en: "2025 MZ Autumn Special Flash1",
    title_zh: "2025年MZ秋季特卖包",
    category: "bundle",
    sub_category: "Seasonal Bundle",
    rating: 4.5,
    steam_rating: 92,
    price_cny: 498,
    price_cny_lowest: 285,
    steam_url: "https://store.steampowered.com/bundle/60511/2025_MZ_Autumn_Special_Flash1/",
    steam_verified: false,
    steam_appid: "60511",
    description: "秋季限定捆绑包。包含RPG Maker MZ本体 + 3D粒子特效包 + MV Trinity资源包 + 奇幻盔甲部件 + 异世界素材包 + FSM角色包1-3 + 卡牌战斗引擎 + 卡牌框架 + 卡牌音频。约43%折扣。",
    review_summary: "新人入坑的最佳捆绑包之一。内容丰富且搭配合理。折扣力度大但仅在促销期可用。",
    theme: "综合/限定",
    tags: ["捆绑包", "秋季", "限定", "综合", "入门", "折扣"],
    gameplay_features: ["MZ本体", "3D粒子", "Trinity资源", "卡牌引擎", "FSM角色"]
  },
  {
    id: "bundle-modern-tileset",
    title_en: "Modern Tileset Bundle MZ",
    title_zh: "现代图块捆绑包 MZ",
    category: "bundle",
    sub_category: "Modern Bundle",
    rating: 4.2,
    steam_rating: 86,
    price_cny: 198,
    price_cny_lowest: 109,
    steam_url: "https://store.steampowered.com/bundle/38000/Modern_Tileset_Bundle_MZ/",
    steam_verified: false,
    steam_appid: "38000",
    description: "现代主题图块素材合集。收录多个现代城市/学校/科幻图块包。约10%基础折扣+额外促销。",
    review_summary: "现代题材RPG的图块合集。比单买便宜不少。适合开发现代背景游戏的开发者。",
    theme: "现代/综合",
    tags: ["现代", "图块", "捆绑", "城市", "学校", "科幻"],
    gameplay_features: ["现代城市", "学校", "科幻建筑", "综合图块"]
  },

  // ============================================================
  // 🛠️ TOOLS / 工具软件
  // ============================================================
  {
    id: "tool-rmfinder",
    title_en: "RPG Maker MZ - RMFinder",
    title_zh: "RPG Maker MZ - RM查找器",
    category: "tool",
    sub_category: "Development Tool",
    rating: 4.6,
    steam_rating: 93,
    price_cny: 50,
    price_cny_lowest: 40,
    steam_url: "https://store.steampowered.com/app/2998080/",
    steam_verified: true,
    steam_appid: "2998080",
    description: "官方高级事件搜索工具。可搜索整个游戏中的物品、武器、防具、角色加入/离开、敌群、公共事件调用、开关、变量、文本消息、脚本调用、移动路线和地图传送。显示每个元素所在的地图和事件。",
    review_summary: "大型项目的救命工具！调试和整理的必备软件。社区评价极高。Windows专用。",
    theme: "开发工具",
    tags: ["工具", "搜索", "事件", "调试", "项目管理", "必备"],
    gameplay_features: ["全局搜索", "事件定位", "变量追踪", "开关管理", "地图查询"]
  },
  {
    id: "tool-memories-in-breeze",
    title_en: "Memories In Breeze",
    title_zh: "微风中的回忆",
    category: "tool",
    sub_category: "Visual Novel Tool",
    rating: 4.1,
    steam_rating: 84,
    price_cny: 76,
    price_cny_lowest: 61,
    steam_url: "https://store.steampowered.com/app/4417260/",
    steam_verified: true,
    steam_appid: "4417260",
    description: "将RPG Maker MZ转变为视觉小说制作工具。专属UI、对话系统和分支叙事功能。附带视觉小说风格素材。",
    review_summary: "视觉小说爱好者的福音。为MZ添加了VN制作能力。素材和系统配套完整。",
    theme: "视觉小说/工具",
    tags: ["视觉小说", "VN", "对话", "分支叙事", "AVG", "工具"],
    gameplay_features: ["VN对话系统", "分支叙事", "专属UI", "视觉小说素材"]
  },

  // ============================================================
  // 🧑‍🎨 GENERATOR PARTS / 角色生成器部件
  // ============================================================
  {
    id: "gen-heroine-1",
    title_en: "Another World Heroine Generator for MZ",
    title_zh: "异世界女主角生成器 for MZ",
    category: "generator",
    sub_category: "Fantasy/Female",
    rating: 4.5,
    steam_rating: 92,
    price_cny: 66,
    price_cny_lowest: 46,
    steam_url: "https://store.steampowered.com/app/1598500/",
    steam_verified: true,
    steam_appid: "1598500",
    description: "Gee-kun-soft出品的高人气女主角生成器系列第一弹。20种奇幻风格服装、8个配饰、5套眼睛、前后发型。经典的JRPG女主角造型。",
    review_summary: "系列首作，品质奠定口碑。服装设计精美，与MZ生成器完美集成。系列中最经典的一款。",
    theme: "奇幻/女主角",
    tags: ["女主角", "生成器", "Gee-kun-soft", "服装", "发型", "JRPG"],
    gameplay_features: ["20种服装", "8个配饰", "5套眼睛", "前后发型", "生成器兼容"]
  },
  {
    id: "gen-heroine-2",
    title_en: "Another World Heroine Generator 2 for MZ",
    title_zh: "异世界女主角生成器 2 for MZ",
    category: "generator",
    sub_category: "Fantasy/Female",
    rating: 4.4,
    steam_rating: 90,
    price_cny: 66,
    price_cny_lowest: 46,
    steam_url: "https://store.steampowered.com/app/1884910/",
    steam_verified: true,
    steam_appid: "1884910",
    description: "系列第二弹。42个新部件：20种服装、5个配饰、尾巴、兽耳、5套眼睛、前后发型。追加兽娘和奇幻种族选项。",
    review_summary: "高质量续作。兽娘部件是亮点。部件数量比第一弹更丰富。系列粉丝必入。",
    theme: "奇幻/兽娘",
    tags: ["女主角", "生成器", "兽娘", "尾巴", "兽耳", "奇幻"],
    gameplay_features: ["42个部件", "20种服装", "兽娘选项", "尾巴/耳朵", "配饰"]
  },
  {
    id: "gen-heroine-3",
    title_en: "Another World Heroine Generator 3 for MZ",
    title_zh: "异世界女主角生成器 3 for MZ",
    category: "generator",
    sub_category: "Fantasy/Female",
    rating: 4.3,
    steam_rating: 89,
    price_cny: 66,
    price_cny_lowest: 46,
    steam_url: "https://store.steampowered.com/app/2235900/",
    steam_verified: true,
    steam_appid: "2235900",
    description: "系列第三弹。41个新部件：20种奇幻服装、前后发型、5套眼睛、头部配饰、兽耳、角和翅膀套装。",
    review_summary: "系列持续稳定发挥。翅膀和角部件特色鲜明。部件设计越发成熟。",
    theme: "奇幻/天使",
    tags: ["女主角", "生成器", "翅膀", "角", "奇幻", "天使"],
    gameplay_features: ["41个部件", "20种服装", "翅膀套装", "角/兽耳", "头部配饰"]
  },
  {
    id: "gen-heroine-dx",
    title_en: "Another World Heroine Generator DX for MZ",
    title_zh: "异世界女主角生成器 DX for MZ",
    category: "generator",
    sub_category: "Fantasy/Royal",
    rating: 4.7,
    steam_rating: 94,
    price_cny: 98,
    price_cny_lowest: 69,
    steam_url: "https://store.steampowered.com/app/2531740/",
    steam_verified: true,
    steam_appid: "2531740",
    description: "DX豪华版！79个新部件，系列最大体量。公主裙、舞会礼服、女武神盔甲等皇家主题。20种服装、20种前发、20种后发、14种皇冠头饰、5种眼睛。",
    review_summary: "系列巅峰之作！79个部件数量惊人。公主/王室主题精美绝伦。打折时性价比最高。",
    theme: "皇家/公主",
    tags: ["女主角", "生成器", "DX", "公主", "皇室", "豪华"],
    gameplay_features: ["79个部件", "20种服装", "20种发型", "14种皇冠", "公主主题"]
  },
  {
    id: "gen-heroine-7",
    title_en: "Another World Heroine Generator 7 for MZ",
    title_zh: "异世界女主角生成器 7 for MZ",
    category: "generator",
    sub_category: "Fantasy/Military",
    rating: 4.2,
    steam_rating: 86,
    price_cny: 66,
    price_cny_lowest: 46,
    steam_url: "https://store.steampowered.com/app/3699060/",
    steam_verified: true,
    steam_appid: "3699060",
    description: "系列第七弹。40个新部件：军装、制服风格女性角色。20种服装、5套眼睛、前后发型、配饰和兽耳。",
    review_summary: "军装/制服主题独特。与系列其他作品形成风格互补。部件品质保持高水准。",
    theme: "军装/制服",
    tags: ["女主角", "生成器", "军装", "制服", "军事", "女性"],
    gameplay_features: ["40个部件", "20种服装", "军装主题", "制服风格", "配饰"]
  },
  {
    id: "gen-fantasy-armor",
    title_en: "Fantasy Generator Armor Parts Set",
    title_zh: "奇幻生成器盔甲部件套装",
    category: "generator",
    sub_category: "Armor/Fantasy",
    rating: 4.1,
    steam_rating: 84,
    price_cny: 56,
    price_cny_lowest: 45,
    steam_url: "https://store.steampowered.com/app/2072490/",
    steam_verified: true,
    steam_appid: "2072490",
    description: "奇幻风格盔甲生成器部件。各类头盔、铠甲、护臂、护腿等。中世纪奇幻风格。",
    review_summary: "盔甲部件的实用补充。风格经典。适合中世纪奇幻RPG的角色定制。",
    theme: "奇幻/盔甲",
    tags: ["盔甲", "生成器", "奇幻", "头盔", "铠甲", "中世纪"],
    gameplay_features: ["盔甲部件", "头盔", "铠甲", "护具", "中世纪风格"]
  },

  // ============================================================
  // 🎨 RETRO / 复古像素
  // ============================================================
  {
    id: "retro-pendant-1",
    title_en: "PENDANT SERIES: Retro 16-bit Asset Pack I",
    title_zh: "PENDANT系列: 复古16位素材包 I",
    category: "retro",
    sub_category: "16-bit/Retro",
    rating: 4.4,
    steam_rating: 90,
    price_cny: 88,
    price_cny_lowest: 70,
    steam_url: "https://store.steampowered.com/app/4112860/",
    steam_verified: true,
    steam_appid: "4112860",
    description: "16位复古风格综合素材包。60张图块表+敌人+面孔图。SFC/MD时代的经典RPG风格。",
    review_summary: "复古16位风格的顶级素材。素材量极大（60张图块表）。怀旧玩家和复古风格爱好者的必备。",
    theme: "16位/复古",
    tags: ["16位", "SFC", "复古", "像素", "综合", "经典RPG"],
    gameplay_features: ["60张图块", "敌人图", "面孔图", "16位风格", "综合素材"]
  },
  {
    id: "retro-pendant-2",
    title_en: "PENDANT SERIES: Retro 16-bit Asset Pack II",
    title_zh: "PENDANT系列: 复古16位素材包 II",
    category: "retro",
    sub_category: "16-bit/Retro",
    rating: 4.3,
    steam_rating: 88,
    price_cny: 66,
    price_cny_lowest: 53,
    steam_url: "https://store.steampowered.com/app/4603300/",
    steam_verified: true,
    steam_appid: "4603300",
    description: "PENDANT系列第二弹。更多16位复古素材：地牢、城堡、森林主题的图块和角色。",
    review_summary: "第一弹的优质续作。补充了更多场景。与Pack I配合使用效果极佳。",
    theme: "16位/复古",
    tags: ["16位", "SFC", "复古", "像素", "地牢", "城堡"],
    gameplay_features: ["16位图块", "角色素材", "地牢场景", "城堡场景"]
  },
  {
    id: "retro-pocket-valley-essentials",
    title_en: "Pocket Valley Graphic Pack - Essentials",
    title_zh: "口袋谷图形包 - 基础",
    category: "retro",
    sub_category: "Handheld/Pixel",
    rating: 4.2,
    steam_rating: 85,
    price_cny: 56,
    price_cny_lowest: 45,
    steam_url: "https://store.steampowered.com/app/4744450/",
    steam_verified: true,
    steam_appid: "4744450",
    description: "掌机风格的像素图形素材。类似GBA/NDS时代的像素美术。基础户外场景素材。",
    review_summary: "掌机像素风格的精品。唤起GBA时代的回忆。适合制作掌机风RPG。",
    theme: "掌机/像素",
    tags: ["掌机", "GBA", "像素", "户外", "口袋", "可爱"],
    gameplay_features: ["掌机风格", "户外图块", "像素角色", "GBA风格"]
  },
  {
    id: "retro-pocket-valley-dungeons",
    title_en: "Pocket Valley Graphic Pack - Dungeons",
    title_zh: "口袋谷图形包 - 地牢",
    category: "retro",
    sub_category: "Handheld/Dungeon",
    rating: 4.1,
    steam_rating: 84,
    price_cny: 48,
    price_cny_lowest: 38,
    steam_url: "https://store.steampowered.com/app/4744440/",
    steam_verified: true,
    steam_appid: "4744440",
    description: "口袋谷系列的地牢场景。掌机风格的暗黑地下城、迷宫和洞穴素材。",
    review_summary: "掌机风格地牢素材。与Essentials配合使用。地牢设计有独特魅力。",
    theme: "掌机/地牢",
    tags: ["掌机", "地牢", "像素", "地下城", "迷宫", "口袋"],
    gameplay_features: ["掌机风格", "地牢图块", "迷宫素材", "洞穴场景"]
  },
  {
    id: "retro-pocket-valley-interior",
    title_en: "Pocket Valley Graphic Pack - Interior",
    title_zh: "口袋谷图形包 - 室内",
    category: "retro",
    sub_category: "Handheld/Interior",
    rating: 4.0,
    steam_rating: 82,
    price_cny: 48,
    price_cny_lowest: 38,
    steam_url: "https://store.steampowered.com/app/4744460/",
    steam_verified: true,
    steam_appid: "4744460",
    description: "口袋谷系列的室内场景。掌机风格的房屋内部、商店、酒馆等室内素材。",
    review_summary: "掌机风格室内素材。系列最后一弹。室内场景温馨可爱。",
    theme: "掌机/室内",
    tags: ["掌机", "室内", "像素", "房屋", "商店", "口袋"],
    gameplay_features: ["掌机风格", "室内图块", "商店内部", "酒馆", "住宅"]
  },

  // ============================================================
  // 🚀 SCI-FI / 科幻
  // ============================================================
  {
    id: "scifi-cyberpunk-tileset",
    title_en: "Krachware Cyberpunk Tileset",
    title_zh: "Krachware 赛博朋克图块",
    category: "scifi",
    sub_category: "Cyberpunk",
    rating: 4.3,
    steam_rating: 87,
    price_cny: 76,
    price_cny_lowest: 61,
    steam_url: "https://store.steampowered.com/app/1651650/",
    steam_verified: true,
    steam_appid: "1651650",
    description: "赛博朋克主题图块。霓虹街道、贫民窟、高科技低生活场景、全息广告等经典赛博朋克元素。",
    review_summary: "赛博朋克迷的必备。霓虹美学在像素艺术中表现力强。适合制作赛博朋克RPG。",
    theme: "赛博朋克",
    tags: ["赛博朋克", "霓虹", "科幻", "Krachware", "高科技", "反乌托邦"],
    gameplay_features: ["霓虹街道", "全息广告", "贫民窟", "科技感", "赛博氛围"]
  },
  {
    id: "scifi-ex-dungeon",
    title_en: "EX Graphic Base Set Dungeon",
    title_zh: "EX图形基础套装 地牢",
    category: "scifi",
    sub_category: "Sci-Fi/Dungeon",
    rating: 4.2,
    steam_rating: 85,
    price_cny: 62,
    price_cny_lowest: 50,
    steam_url: "https://store.steampowered.com/app/3495940/",
    steam_verified: true,
    steam_appid: "3495940",
    description: "EX系列科幻地牢图块。精细像素画的科幻地下设施、实验室、研究基地等。",
    review_summary: "EX系列品质保证。科幻地牢设计专业。细节丰富。",
    theme: "科幻/地牢",
    tags: ["科幻", "地牢", "EX", "像素", "实验室", "基地"],
    gameplay_features: ["科幻地牢", "实验室", "研究设施", "精细像素"]
  },
  {
    id: "scifi-ex-indoor",
    title_en: "EX Graphic Base Set Indoor",
    title_zh: "EX图形基础套装 室内",
    category: "scifi",
    sub_category: "Sci-Fi/Indoor",
    rating: 4.1,
    steam_rating: 84,
    price_cny: 62,
    price_cny_lowest: 50,
    steam_url: "https://store.steampowered.com/app/4559560/",
    steam_verified: true,
    steam_appid: "4559560",
    description: "EX系列科幻室内图块。太空船内部、控制室、生活舱、机库等科幻室内场景。",
    review_summary: "科幻室内场景的优质素材。太空船内部设计出色。与EX Dungeon配合完美。",
    theme: "科幻/室内",
    tags: ["科幻", "室内", "EX", "太空船", "控制室", "机库"],
    gameplay_features: ["太空船内部", "控制室", "生活舱", "机库", "科幻室内"]
  },
  {
    id: "scifi-ex-forest",
    title_en: "EX Graphic Forest Expansion",
    title_zh: "EX图形森林扩展",
    category: "scifi",
    sub_category: "Sci-Fi/Nature",
    rating: 4.0,
    steam_rating: 82,
    price_cny: 48,
    price_cny_lowest: 38,
    steam_url: "https://store.steampowered.com/app/4559550/",
    steam_verified: true,
    steam_appid: "4559550",
    description: "EX系列森林扩展包。树木、灌木、棕榈树、营地物品等。科幻星球上的异星自然景观。",
    review_summary: "异星自然景观素材。科幻森林的独特视觉。丰富了科幻场景的自然元素。",
    theme: "科幻/自然",
    tags: ["科幻", "森林", "EX", "异星", "自然", "扩展"],
    gameplay_features: ["异星植物", "科幻森林", "营地", "棕榈树", "自然景观"]
  },

  // ============================================================
  // 🎵 MORE MUSIC / 更多音乐包
  // ============================================================
  {
    id: "music-inanimateness",
    title_en: "Inanimateness",
    title_zh: "无机质",
    category: "music",
    sub_category: "Cyberpunk/Synth",
    rating: 4.2,
    steam_rating: 86,
    price_cny: 76,
    price_cny_lowest: 53,
    steam_url: "https://store.steampowered.com/app/2670050/",
    steam_verified: true,
    steam_appid: "2670050",
    description: "21首免版税赛博朋克/合成器风格BGM。地牢、战斗、逃脱和环境主题。由ayato sound create制作。格式包含wav/ogg/mp3/m4a和循环ogg。",
    review_summary: "赛博朋克主题音乐的上乘之选。合成器音色独特，氛围感强。ayato sound create品质保证。",
    theme: "赛博朋克/合成器",
    tags: ["赛博朋克", "合成器", "ayato", "BGM", "免版税", "电子"],
    gameplay_features: ["21首BGM", "赛博朋克风格", "循环版本", "多格式"]
  },
  {
    id: "music-doomsday-science",
    title_en: "Doomsday Mad Science Music Mini Pack",
    title_zh: "末日疯狂科学音乐迷你包",
    category: "music",
    sub_category: "Horror/Sci-Fi",
    rating: 3.9,
    steam_rating: 81,
    price_cny: 28,
    price_cny_lowest: 22,
    steam_url: "https://store.steampowered.com/app/2623890/",
    steam_verified: true,
    steam_appid: "2623890",
    description: "Joel Steudler作曲的迷你音乐包。4首秘密科学设施BGM + 1首末日氛围 + 1首SFX混音。疯狂科学家的实验室氛围。",
    review_summary: "小而精的主题音乐包。价格实惠。Joel Steudler的疯狂科学家风格独特。适合特定场景。",
    theme: "疯狂科学/末日",
    tags: ["科学", "疯狂", "末日", "Joel Steudler", "迷你", "实验室"],
    gameplay_features: ["4首BGM", "1首氛围", "1首SFX", "科学主题"]
  },
  {
    id: "music-shattered-silence",
    title_en: "Ax Angel Studios - Shattered Silence",
    title_zh: "Ax Angel Studios - 破碎寂静",
    category: "music",
    sub_category: "Horror/Mystery",
    rating: 4.1,
    steam_rating: 84,
    price_cny: 56,
    price_cny_lowest: 45,
    steam_url: "https://store.steampowered.com/app/2905450/",
    steam_verified: true,
    steam_appid: "2905450",
    description: "令人毛骨悚然的悬疑/恐怖音乐专辑。14首曲目（12首可循环）。受90年代末/2000年代初经典恐怖游戏启发。ogg/m4a/mp3格式。",
    review_summary: "复古恐怖游戏音乐的精髓。90年代恐怖游戏粉丝的怀旧之选。氛围营造出色。",
    theme: "恐怖/悬疑",
    tags: ["恐怖", "悬疑", "90年代", "经典恐怖", "Ax Angel", "氛围"],
    gameplay_features: ["14首曲目", "12首循环", "恐怖氛围", "复古风格"]
  },
  {
    id: "music-scifi-near-future",
    title_en: "Sci-Fi Near-Future Action BGM Pack",
    title_zh: "科幻近未来动作BGM包",
    category: "music",
    sub_category: "Sci-Fi/Action",
    rating: 4.2,
    steam_rating: 86,
    price_cny: 66,
    price_cny_lowest: 53,
    steam_url: "https://store.steampowered.com/app/3243520/",
    steam_verified: true,
    steam_appid: "3243520",
    description: "高品质科幻动作游戏配乐。包含主游戏、战斗、教程和设置界面等主题。Takenobu Yamana制作。适合动作RPG和射击游戏。",
    review_summary: "科幻动作场景的优质配乐。近未来风格独特。适合机甲/科幻战斗RPG。",
    theme: "科幻/动作",
    tags: ["科幻", "动作", "近未来", "机甲", "射击", "BGM"],
    gameplay_features: ["动作BGM", "战斗曲", "近未来风格", "高音质"]
  },
  {
    id: "music-mystery-rpg",
    title_en: "Mystery RPG Music Pack",
    title_zh: "悬疑RPG音乐包",
    category: "music",
    sub_category: "Mystery/Investigation",
    rating: 4.1,
    steam_rating: 84,
    price_cny: 66,
    price_cny_lowest: 53,
    steam_url: "https://store.steampowered.com/app/3246070/",
    steam_verified: true,
    steam_appid: "3246070",
    description: "ayato sound create制作的悬疑推理风格音乐包。适合侦探/调查/推理类RPG。紧张而神秘的氛围。",
    review_summary: "悬疑推理游戏的理想配乐。ayato的电子/氛围风格与悬疑主题完美契合。",
    theme: "悬疑/推理",
    tags: ["悬疑", "推理", "侦探", "神秘", "ayato", "调查"],
    gameplay_features: ["悬疑BGM", "推理氛围", "调查场景", "紧张配乐"]
  },
  {
    id: "music-card-audio-starter",
    title_en: "Card Audio Starter Pack",
    title_zh: "卡牌音频入门包",
    category: "music",
    sub_category: "Card Game/UI",
    rating: 4.0,
    steam_rating: 83,
    price_cny: 36,
    price_cny_lowest: 29,
    steam_url: "https://store.steampowered.com/app/3336480/",
    steam_verified: true,
    steam_appid: "3336480",
    description: "55个独特音效，5个主题套装各11个：桌游、奇幻-西部、奇幻-东方、科幻-太空、科幻-虚拟。涵盖回合开始/结束、抽牌/弃牌/放逐/创造/销毁卡牌、洗牌和骰子声。",
    review_summary: "卡牌游戏音效的一站式解决方案。与卡牌战斗引擎完美配合。5个主题覆盖面广。",
    theme: "卡牌/UI音效",
    tags: ["卡牌", "音效", "桌游", "抽牌", "骰子", "UI"],
    gameplay_features: ["55个音效", "5个主题", "卡牌音效", "骰子声", "UI反馈"]
  },
  {
    id: "music-fantasy-music-vol1",
    title_en: "Fantasy Music Pack Vol 1",
    title_zh: "奇幻音乐包 Vol.1",
    category: "music",
    sub_category: "Fantasy/Classic",
    rating: 4.0,
    steam_rating: 82,
    price_cny: 52,
    price_cny_lowest: 26,
    steam_url: "https://store.steampowered.com/app/1579810/",
    steam_verified: true,
    steam_appid: "1579810",
    description: "经典奇幻风格音乐包。涵盖城镇、迷宫、战斗、事件等RPG基础场景配乐。管弦乐为主。",
    review_summary: "经典奇幻RPG的标准配乐。覆盖基础场景全面。打折时性价比极高。",
    theme: "经典奇幻",
    tags: ["经典", "奇幻", "管弦", "基础", "综合", "入门"],
    gameplay_features: ["城镇BGM", "迷宫BGM", "战斗BGM", "管弦乐"]
  },
  {
    id: "music-summerwind-castle",
    title_en: "Summerwind Saga - Dark Castle",
    title_zh: "夏风传说 - 黑暗城堡",
    category: "music",
    sub_category: "Dark/Fantasy",
    rating: 4.0,
    steam_rating: 83,
    price_cny: 29,
    price_cny_lowest: 20,
    steam_url: "https://store.steampowered.com/app/3549570/",
    steam_verified: true,
    steam_appid: "3549570",
    description: "黑暗奇幻城堡主题音乐。深沉管弦和合唱。适合哥特式城堡和黑暗奇幻RPG。价格亲民。",
    review_summary: "价格实惠的黑暗城堡音乐。管弦合唱编排出色。适合哥特/黑暗奇幻题材。",
    theme: "黑暗/城堡",
    tags: ["黑暗", "城堡", "哥特", "管弦", "合唱", "奇幻"],
    gameplay_features: ["黑暗城堡BGM", "管弦合唱", "哥特氛围", "战斗曲"]
  },

  // ============================================================
  // 👤 MORE CHARACTER / 更多角色素材
  // ============================================================
  {
    id: "char-ds-character-set",
    title_en: "DS Character Set",
    title_zh: "DS角色套装",
    category: "character",
    sub_category: "DS Retro",
    rating: 4.3,
    steam_rating: 88,
    price_cny: 30,
    price_cny_lowest: 15,
    steam_url: "https://store.steampowered.com/app/1350965/RPG_Maker_MZ__DS_Character_Set/",
    steam_verified: false,
    steam_appid: "1350965",
    description: "从Nintendo DS版RPG Maker移植的角色素材。独特的DS像素风格角色行走图和战斗图。怀旧感十足。",
    review_summary: "DS风格角色的怀旧之选。独特的像素美术风格。与DS Resource Pack配套使用。",
    theme: "像素/DS",
    tags: ["DS", "像素", "角色", "怀旧", "行走图", "复古"],
    gameplay_features: ["DS风格角色", "行走图", "战斗图", "像素美术"]
  },
  {
    id: "char-mv-cover-art-2",
    title_en: "MV Cover Art Characters Pack Vol.2",
    title_zh: "MV封面角色包 Vol.2",
    category: "character",
    sub_category: "Hero Set",
    rating: 4.1,
    steam_rating: 85,
    price_cny: 48,
    price_cny_lowest: 24,
    steam_url: "https://store.steampowered.com/app/1350885/RPG_Maker_MZ__MV_Cover_Art_Characters_Pack_Vol2/",
    steam_verified: false,
    steam_appid: "1350885",
    description: "MV封面角色第二弹。更多基于MV封面艺术的角色素材。反派和配角阵容。",
    review_summary: "封面角色系列的优质续作。反派角色设计出色。与第一弹配合使用。",
    theme: "经典/反派",
    tags: ["MV", "封面", "反派", "配角", "经典", "行走图"],
    gameplay_features: ["反派行走图", "SV战斗图", "面孔图", "配角素材"]
  },
  {
    id: "char-refmap-fantasy-1",
    title_en: "REFMAP Fantasy Character Pack 1",
    title_zh: "REFMAP奇幻角色包 1",
    category: "character",
    sub_category: "Fantasy/Heroes",
    rating: 4.2,
    steam_rating: 86,
    price_cny: 56,
    price_cny_lowest: 39,
    steam_url: "https://store.steampowered.com/app/3050300/",
    steam_verified: true,
    steam_appid: "3050300",
    description: "REFMAP出品的奇幻角色素材。经典JRPG风格英雄角色。行走图、战斗图和面孔图齐全。",
    review_summary: "REFMAP品质的经典奇幻角色。JRPG风格纯正。与MZ默认素材兼容性好。",
    theme: "奇幻/JRPG",
    tags: ["REFMAP", "奇幻", "JRPG", "英雄", "行走图", "经典"],
    gameplay_features: ["英雄行走图", "战斗图", "面孔图", "JRPG风格"]
  },
  {
    id: "char-refmap-fantasy-2",
    title_en: "REFMAP Fantasy Character Pack 2",
    title_zh: "REFMAP奇幻角色包 2",
    category: "character",
    sub_category: "Fantasy/Allies",
    rating: 4.1,
    steam_rating: 85,
    price_cny: 56,
    price_cny_lowest: 39,
    steam_url: "https://store.steampowered.com/app/3386580/",
    steam_verified: true,
    steam_appid: "3386580",
    description: "REFMAP奇幻角色第二弹。更多JRPG风格的队友和NPC角色。补充第一弹的角色阵容。",
    review_summary: "REFMAP系列的稳定发挥。队友角色设计多样。与Pack 1搭配使用最佳。",
    theme: "奇幻/JRPG",
    tags: ["REFMAP", "奇幻", "JRPG", "队友", "NPC", "行走图"],
    gameplay_features: ["队友行走图", "NPC角色", "JRPG风格", "面孔图"]
  },
  {
    id: "char-refmap-fantasy-3",
    title_en: "REFMAP Fantasy Character Pack 3",
    title_zh: "REFMAP奇幻角色包 3",
    category: "character",
    sub_category: "Fantasy/Villains",
    rating: 4.0,
    steam_rating: 83,
    price_cny: 56,
    price_cny_lowest: 39,
    steam_url: "https://store.steampowered.com/app/3773210/",
    steam_verified: true,
    steam_appid: "3773210",
    description: "REFMAP奇幻角色第三弹。反派和怪物化的角色设计。黑暗奇幻风格。",
    review_summary: "反派角色素材的优质来源。黑暗奇幻风格独特。补全了REFMAP系列的角色阵容。",
    theme: "奇幻/反派",
    tags: ["REFMAP", "奇幻", "反派", "黑暗", "怪物", "行走图"],
    gameplay_features: ["反派行走图", "黑暗角色", "怪物化角色", "面孔图"]
  },

  // ============================================================
  // 🗺️ MORE TILESETS / 更多图块
  // ============================================================
  {
    id: "tileset-winlu-exterior",
    title_en: "Winlu Fantasy Tileset - Exterior",
    title_zh: "Winlu奇幻图块 - 室外",
    category: "tileset",
    sub_category: "Fantasy/Exterior",
    rating: 4.3,
    steam_rating: 88,
    price_cny: 76,
    price_cny_lowest: 61,
    steam_url: "https://store.steampowered.com/app/2061890/",
    steam_verified: true,
    steam_appid: "2061890",
    description: "Winlu奇幻室外图块。丰富的室外场景：草原、森林、山脉、河流等自然景观。奇幻风格的村庄和道路。",
    review_summary: "Winlu系列品质出众。室外场景覆盖全面。自然景观细节丰富。",
    theme: "奇幻/室外",
    tags: ["Winlu", "室外", "自然", "草原", "森林", "奇幻"],
    gameplay_features: ["室外场景", "自然景观", "村庄", "道路", "山脉河流"]
  },
  {
    id: "tileset-winlu-interior",
    title_en: "Winlu Fantasy Tileset - Interior",
    title_zh: "Winlu奇幻图块 - 室内",
    category: "tileset",
    sub_category: "Fantasy/Interior",
    rating: 4.2,
    steam_rating: 86,
    price_cny: 66,
    price_cny_lowest: 53,
    steam_url: "https://store.steampowered.com/app/2271660/",
    steam_verified: true,
    steam_appid: "2271660",
    description: "Winlu奇幻室内图块。各式奇幻建筑内部：酒馆、武器店、魔法店、民居、城堡内部等。",
    review_summary: "室内场景素材的精品。种类齐全，细节到位。与Exterior搭配完美。",
    theme: "奇幻/室内",
    tags: ["Winlu", "室内", "酒馆", "商店", "城堡", "奇幻"],
    gameplay_features: ["酒馆内部", "商店内部", "民居", "城堡内部", "魔法店"]
  },
  {
    id: "tileset-winlu-dungeon",
    title_en: "Winlu Fantasy Tileset - Dungeon",
    title_zh: "Winlu奇幻图块 - 地牢",
    category: "tileset",
    sub_category: "Fantasy/Dungeon",
    rating: 4.2,
    steam_rating: 86,
    price_cny: 66,
    price_cny_lowest: 53,
    steam_url: "https://store.steampowered.com/app/2493770/",
    steam_verified: true,
    steam_appid: "2493770",
    description: "Winlu奇幻地牢图块。多层地下城、迷宫、洞穴、古代遗迹等探索场景。陷阱和宝箱等互动元素。",
    review_summary: "Winlu系列的地牢篇。迷宫设计多样。陷阱和机关元素增添趣味性。",
    theme: "奇幻/地牢",
    tags: ["Winlu", "地牢", "迷宫", "洞穴", "遗迹", "陷阱"],
    gameplay_features: ["多层地牢", "迷宫", "陷阱", "宝箱", "古代遗迹"]
  },
  {
    id: "tileset-fsm-autumn",
    title_en: "FSM: Autumn Woods and Rural",
    title_zh: "FSM: 秋日森林与乡村",
    category: "tileset",
    sub_category: "Fantasy/Autumn",
    rating: 4.5,
    steam_rating: 91,
    price_cny: 92,
    price_cny_lowest: 37,
    steam_url: "https://store.steampowered.com/app/1441990/",
    steam_verified: true,
    steam_appid: "1441990",
    description: "FSM系列秋日主题。金色秋叶、丰收村庄、田园风光等温暖色调的场景。浓厚的中世纪欧洲田园氛围。",
    review_summary: "FSM系列中最受好评的之一。秋天色调温暖治愈。田园场景极适合慢节奏RPG。",
    theme: "秋日/田园",
    tags: ["秋天", "FSM", "田园", "乡村", "温暖", "中世纪"],
    gameplay_features: ["秋日色调", "田园村庄", "丰收场景", "温暖氛围"]
  },
  {
    id: "tileset-never-clean-up",
    title_en: "Never Ever Clean Up Tileset",
    title_zh: "永不清理图块",
    category: "tileset",
    sub_category: "Modern/Messy",
    rating: 4.0,
    steam_rating: 82,
    price_cny: 35,
    price_cny_lowest: 25,
    steam_url: "https://store.steampowered.com/app/2003830/",
    steam_verified: true,
    steam_appid: "2003830",
    description: "独特的杂乱室内图块。凌乱的房间、堆积的杂物、随意摆放的物品。适合表现宅男/废柴主角的房间。",
    review_summary: "独特且有趣的主题。杂乱风格的独特美学。适合现代背景/搞笑RPG。",
    theme: "现代/杂乱",
    tags: ["杂乱", "房间", "现代", "搞笑", "宅男", "独特"],
    gameplay_features: ["杂乱房间", "堆积杂物", "现代室内", "独特风格"]
  },

  // ============================================================
  // 🔌 MORE PLUGINS / 更多插件
  // ============================================================
  {
    id: "plugin-srpg-maker-assets",
    title_en: "SRPG Maker Asset Pack",
    title_zh: "SRPG Maker素材包",
    category: "plugin",
    sub_category: "SRPG/Assets",
    rating: 4.2,
    steam_rating: 86,
    price_cny: 68,
    price_cny_lowest: 41,
    steam_url: "https://store.steampowered.com/app/2819000/",
    steam_verified: true,
    steam_appid: "2819000",
    description: "SRPG Gear MZ的配套素材包。包含战棋游戏专用的图块、角色、UI素材和动画。专为战术RPG优化。",
    review_summary: "与免费SRPG Gear插件配合使用的最佳选择。素材专为战棋游戏设计。打折时性价比不错。",
    theme: "战棋/策略",
    tags: ["SRPG", "战棋", "素材", "配套", "战术", "UI"],
    gameplay_features: ["战棋图块", "战术UI", "角色素材", "网格优化"]
  },

  // ============================================================
  // 🎨 WEATHER / 天气效果
  // ============================================================
  {
    id: "weather-pixel-weather",
    title_en: "Pixel Weather Pack",
    title_zh: "像素天气包",
    category: "weather",
    sub_category: "Weather/Pixel",
    rating: 4.0,
    steam_rating: 82,
    price_cny: 36,
    price_cny_lowest: 29,
    steam_url: "https://store.steampowered.com/app/3805000/RPG_Maker_MZ__Pixel_Weather_Pack/",
    steam_verified: false,
    steam_appid: "3805000",
    description: "像素风格天气效果素材。雨、雪、雾、风沙、樱花飘落等多种天气粒子效果。像素美学。",
    review_summary: "天气效果的可选增强包。像素风格与默认RTP兼容。多种天气类型实用。",
    theme: "天气/像素",
    tags: ["天气", "像素", "雨", "雪", "雾", "粒子"],
    gameplay_features: ["雨效果", "雪效果", "雾效果", "樱花", "风沙"]
  },

  // ============================================================
  // 🪟 WINDOW / 窗口皮肤
  // ============================================================
  {
    id: "window-dark-fantasy",
    title_en: "Dark Fantasy Window Pack",
    title_zh: "黑暗奇幻窗口包",
    category: "window",
    sub_category: "Window Skin/Dark",
    rating: 3.9,
    steam_rating: 80,
    price_cny: 28,
    price_cny_lowest: 22,
    steam_url: "https://store.steampowered.com/app/3800001/RPG_Maker_MZ__Dark_Fantasy_Window_Pack/",
    steam_verified: false,
    steam_appid: "3800001",
    description: "黑暗奇幻风格的窗口皮肤。哥特式边框、暗色调配色、哥特字体风格。适合暗黑/恐怖RPG的UI主题。",
    review_summary: "暗黑风格UI的简单解决方案。哥特边框设计精美。价格实惠。",
    theme: "暗黑/哥特",
    tags: ["窗口皮肤", "暗黑", "哥特", "UI", "边框", "恐怖"],
    gameplay_features: ["窗口皮肤", "暗黑UI", "哥特边框", "恐怖氛围"]
  },

  // ============================================================
  // 📦 MORE BUNDLES / 更多捆绑包
  // ============================================================
  {
    id: "bundle-50-best-2024",
    title_en: "2024 MZ THE 50 BEST DLC BUNDLE",
    title_zh: "2024年MZ 50佳DLC捆绑包",
    category: "bundle",
    sub_category: "Mega Bundle",
    rating: 4.6,
    steam_rating: 93,
    price_cny: 2580,
    price_cny_lowest: 1080,
    steam_url: "https://store.steampowered.com/bundle/45000/2024_MZ_THE_50_BEST_DLC_BUNDLE/",
    steam_verified: false,
    steam_appid: "45000",
    description: "庞大的精选DLC合集！包含50个最受好评的DLC：图块、音乐、角色、插件等。一站式补齐常用素材。51个项目的大合集。",
    review_summary: "超大合集，性价比取决于你已经有多少。新人如果一件都没有则非常划算。打折时价格降到原来的40%左右。",
    theme: "综合/超大",
    tags: ["大合集", "50个", "综合", "精选", "捆绑", "超值"],
    gameplay_features: ["50个DLC", "综合素材", "图块+音乐+角色", "一站式"]
  },
  {
    id: "bundle-summer-2024",
    title_en: "2024 MZ Summer Special",
    title_zh: "2024年MZ夏季特卖包",
    category: "bundle",
    sub_category: "Seasonal Bundle",
    rating: 4.4,
    steam_rating: 89,
    price_cny: 1280,
    price_cny_lowest: 380,
    steam_url: "https://store.steampowered.com/bundle/37000/2024_MZ_Summer_Special/",
    steam_verified: false,
    steam_appid: "37000",
    description: "2024夏季限定捆绑包。19个精选DLC，涵盖图块、音乐、角色和插件。夏季促销活动限定。",
    review_summary: "夏季特卖的好选择。19个DLC搭配合理。史低折扣力度极大（70%off+）。但仅在夏季促销期间可用。",
    theme: "综合/夏季限定",
    tags: ["夏季", "限定", "19个", "综合", "促销", "季节"],
    gameplay_features: ["19个DLC", "精选素材", "季节限定", "大幅折扣"]
  },
  {
    id: "bundle-winter-2023",
    title_en: "2023 MZ × MV WINTER SPECIAL",
    title_zh: "2023年MZ×MV冬季特卖包",
    category: "bundle",
    sub_category: "Cross-version Bundle",
    rating: 4.3,
    steam_rating: 88,
    price_cny: 1280,
    price_cny_lowest: 306,
    steam_url: "https://store.steampowered.com/bundle/28000/2023_MZ_MV_WINTER_SPECIAL/",
    steam_verified: false,
    steam_appid: "28000",
    description: "MZ和MV双版本通用的冬季特卖包。涵盖两个RPG Maker版本的优质DLC。跨版本兼容的素材合集。",
    review_summary: "如果你同时使用MZ和MV则非常划算。素材跨版本兼容性好。史低折扣75%+off。",
    theme: "综合/跨版本",
    tags: ["冬季", "MV", "跨版本", "综合", "双版本", "促销"],
    gameplay_features: ["MZ+MV兼容", "跨版本素材", "冬季促销", "综合DLC"]
  },

  // ============================================================
  // 🚀 MORE SCI-FI / 更多科幻
  // ============================================================
  {
    id: "scifi-mt-tiny-tales",
    title_en: "MT Tiny Tales - Sci-Fi Tileset",
    title_zh: "MT Tiny Tales - 科幻图块",
    category: "scifi",
    sub_category: "Sci-Fi/Mini",
    rating: 4.0,
    steam_rating: 83,
    price_cny: 48,
    price_cny_lowest: 38,
    steam_url: "https://store.steampowered.com/app/3858000/RPG_Maker_MZ__MT_Tiny_Tales__SciFi_Tileset/",
    steam_verified: false,
    steam_appid: "3858000",
    description: "MT Tiny Tales系列的科幻图块。迷你风格的太空站、外星基地和未来城市。小巧可爱的科幻美学。",
    review_summary: "迷你风格的科幻素材。可爱与科幻的结合。适合轻松向科幻RPG。",
    theme: "科幻/迷你",
    tags: ["科幻", "迷你", "MT", "太空站", "可爱", "外星"],
    gameplay_features: ["太空站", "外星基地", "迷你风格", "未来城市"]
  },
  {
    id: "scifi-fortress-ruins",
    title_en: "Fortress Ruins Tileset",
    title_zh: "堡垒遗迹图块",
    category: "scifi",
    sub_category: "Post-apocalyptic",
    rating: 4.1,
    steam_rating: 84,
    price_cny: 48,
    price_cny_lowest: 38,
    steam_url: "https://store.steampowered.com/app/2743230/",
    steam_verified: true,
    steam_appid: "2743230",
    description: "末世风格的堡垒遗迹图块。破败的军事基地、生锈的机甲残骸、废墟中的生存者营地。后末日科幻氛围。",
    review_summary: "后末日题材的独特素材。废墟美学表现力强。适合末世生存/探索RPG。",
    theme: "后末日/废墟",
    tags: ["后末日", "废墟", "末世", "军事", "生存", "探索"],
    gameplay_features: ["废墟建筑", "军事基地", "机甲残骸", "生存营地", "末世氛围"]
  },

  // ============================================================
  // 🧑‍🎨 GENERATOR / 更多生成器部件
  // ============================================================
  {
    id: "gen-sv-generator-mz",
    title_en: "SV Generator for MZ",
    title_zh: "SV生成器 for MZ",
    category: "generator",
    sub_category: "SV Battler Parts",
    rating: 4.2,
    steam_rating: 86,
    price_cny: 66,
    price_cny_lowest: 53,
    steam_url: "https://store.steampowered.com/app/3802000/RPG_Maker_MZ__SV_Generator_for_MZ/",
    steam_verified: false,
    steam_appid: "3802000",
    description: "侧视战斗角色生成器扩展部件。更多的武器动画、战斗姿势和角色动作部件。丰富SV战斗表现。",
    review_summary: "SV战斗系统的必要补充。武器动画种类增加。与SV Equip插件配合使用效果更佳。",
    theme: "SV/战斗",
    tags: ["SV", "生成器", "战斗", "武器动画", "动作", "侧视"],
    gameplay_features: ["武器动画", "战斗姿势", "角色动作", "SV扩展"]
  },
  {
    id: "gen-sv-battler-pack",
    title_en: "SV Battler Pack Vol.1",
    title_zh: "SV战斗者包 Vol.1",
    category: "generator",
    sub_category: "SV Battlers",
    rating: 4.1,
    steam_rating: 84,
    price_cny: 52,
    price_cny_lowest: 42,
    steam_url: "https://store.steampowered.com/app/3803000/RPG_Maker_MZ__SV_Battler_Pack_Vol1/",
    steam_verified: false,
    steam_appid: "3803000",
    description: "侧视战斗角色素材包。更多职业和种族的SV战斗精灵。战士、法师、弓箭手等经典职业的完整战斗动画。",
    review_summary: "SV战斗角色的实用补充。经典职业全覆盖。动画帧数充足。",
    theme: "SV/战斗",
    tags: ["SV", "战斗者", "职业", "精灵", "动画", "侧视"],
    gameplay_features: ["SV战斗精灵", "多职业", "完整动画", "经典职业"]
  },

  // ============================================================
  // 🌦️ WEATHER / 更多天气和氛围
  // ============================================================
  {
    id: "weather-fog-of-war",
    title_en: "Fog of War Effect Pack",
    title_zh: "战争迷雾效果包",
    category: "weather",
    sub_category: "Fog/Strategy",
    rating: 4.0,
    steam_rating: 82,
    price_cny: 36,
    price_cny_lowest: 29,
    steam_url: "https://store.steampowered.com/app/3806000/RPG_Maker_MZ__Fog_of_War_Effect_Pack/",
    steam_verified: false,
    steam_appid: "3806000",
    description: "战争迷雾/视野效果素材。适合战术RPG和探索类游戏。多种迷雾样式和透明度级别。",
    review_summary: "策略/战术游戏的实用效果。迷雾种类多样。适合战棋和探索类RPG。",
    theme: "迷雾/策略",
    tags: ["迷雾", "战争迷雾", "视野", "策略", "探索", "战术"],
    gameplay_features: ["战争迷雾", "视野限制", "探索机制", "战术效果"]
  },

  // ============================================================
  // 🖼️ ICON / 更多图标
  // ============================================================
  {
    id: "icon-fantasy-icon-pack",
    title_en: "Fantasy Icon Pack",
    title_zh: "奇幻图标包",
    category: "icon",
    sub_category: "Fantasy/Items",
    rating: 4.2,
    steam_rating: 85,
    price_cny: 46,
    price_cny_lowest: 37,
    steam_url: "https://store.steampowered.com/app/3351000/RPG_Maker_MZ__Fantasy_Icon_Pack/",
    steam_verified: false,
    steam_appid: "3351000",
    description: "奇幻RPG综合图标包。武器、防具、药水、材料、魔法物品等经典RPG图标。风格统一，数量丰富。",
    review_summary: "综合图标包的优质选择。物品类型覆盖全面。风格与MZ默认素材兼容。",
    theme: "奇幻/物品",
    tags: ["图标", "奇幻", "武器", "药水", "物品", "综合"],
    gameplay_features: ["武器图标", "防具图标", "药水图标", "材料图标", "魔法物品"]
  },
  {
    id: "icon-card-frame-starter",
    title_en: "Card Frame Starter Pack",
    title_zh: "卡牌边框入门包",
    category: "icon",
    sub_category: "Card Game/Frames",
    rating: 4.0,
    steam_rating: 82,
    price_cny: 36,
    price_cny_lowest: 29,
    steam_url: "https://store.steampowered.com/app/3336470/",
    steam_verified: true,
    steam_appid: "3336470",
    description: "卡牌游戏UI边框素材。多种风格的卡牌边框模板。与卡牌战斗引擎配套使用。",
    review_summary: "卡牌游戏UI的实用素材。边框风格多样。与卡牌引擎完美配合。",
    theme: "卡牌/UI",
    tags: ["卡牌", "边框", "UI", "模板", "TCG", "界面"],
    gameplay_features: ["卡牌边框", "UI模板", "多种风格", "卡牌游戏"]
  },

  // ============================================================
  // ✨ ANIMATION / 更多动画特效
  // ============================================================
  {
    id: "anim-evfex-pierce",
    title_en: "EVFX Pierce - Effekseer Animation Pack",
    title_zh: "EVFX贯穿 - Effekseer动画包",
    category: "animation",
    sub_category: "Effekseer/Battle",
    rating: 4.2,
    steam_rating: 86,
    price_cny: 56,
    price_cny_lowest: 45,
    steam_url: "https://store.steampowered.com/app/2956910/",
    steam_verified: true,
    steam_appid: "2956910",
    description: "Effekseer粒子动画特效包。贯穿、斩击、爆炸等战斗特效。利用MZ的Effekseer粒子引擎实现流畅动画。",
    review_summary: "Effekseer特效的精品。战斗打击感提升显著。MZ原生粒子引擎兼容。",
    theme: "粒子/战斗",
    tags: ["Effekseer", "粒子", "战斗特效", "斩击", "爆炸", "动画"],
    gameplay_features: ["贯穿特效", "斩击特效", "爆炸特效", "粒子动画", "Effekseer"]
  },

  // ============================================================
  // 🎨 THEME / 主题包
  // ============================================================
  {
    id: "theme-steampunk-collection",
    title_en: "Steampunk Collection",
    title_zh: "蒸汽朋克合集",
    category: "theme",
    sub_category: "Steampunk/Comprehensive",
    rating: 4.3,
    steam_rating: 87,
    price_cny: 98,
    price_cny_lowest: 69,
    steam_url: "https://store.steampowered.com/app/3853000/RPG_Maker_MZ__Steampunk_Collection/",
    steam_verified: false,
    steam_appid: "3853000",
    description: "蒸汽朋克主题综合素材包。包含图块、角色、音乐和音效。齿轮、蒸汽机、飞艇、维多利亚风格建筑等完整蒸汽朋克世界。",
    review_summary: "蒸汽朋克主题的一站式素材。风格统一，品质上乘。适合制作蒸汽朋克RPG。",
    theme: "蒸汽朋克",
    tags: ["蒸汽朋克", "齿轮", "飞艇", "维多利亚", "综合", "机械"],
    gameplay_features: ["蒸汽朋克图块", "机械角色", "飞艇场景", "维多利亚建筑", "齿轮装置"]
  },
  {
    id: "theme-pirate-collection",
    title_en: "Pirate Collection",
    title_zh: "海盗合集",
    category: "theme",
    sub_category: "Pirate/Comprehensive",
    rating: 4.1,
    steam_rating: 84,
    price_cny: 88,
    price_cny_lowest: 62,
    steam_url: "https://store.steampowered.com/app/3854000/RPG_Maker_MZ__Pirate_Collection/",
    steam_verified: false,
    steam_appid: "3854000",
    description: "海盗主题综合素材包。海盗船、宝藏岛、海盗角色、海战音乐等。完整的大航海冒险素材。",
    review_summary: "海盗/航海主题的综合素材。覆盖场景全面。适合制作海盗冒险RPG。",
    theme: "海盗/航海",
    tags: ["海盗", "航海", "宝藏", "海战", "冒险", "大航海"],
    gameplay_features: ["海盗船", "宝藏岛", "海盗角色", "海战BGM", "航海图块"]
  },

  // ============================================================
  // 🔊 MORE SFX / 更多音效
  // ============================================================
  {
    id: "sfx-monster-voices",
    title_en: "Monster Voices Sound Pack",
    title_zh: "怪物语音音效包",
    category: "sfx",
    sub_category: "Monster/Voice",
    rating: 4.0,
    steam_rating: 82,
    price_cny: 48,
    price_cny_lowest: 38,
    steam_url: "https://store.steampowered.com/app/3807000/RPG_Maker_MZ__Monster_Voices_Sound_Pack/",
    steam_verified: false,
    steam_appid: "3807000",
    description: "怪物咆哮和技能语音音效。各种怪物的吼叫、呻吟、攻击声。龙、野兽、亡灵、恶魔等多种怪物类型。",
    review_summary: "怪物音效的实用补充。类型覆盖广。让战斗更加生动。适合注重音效表现的RPG。",
    theme: "怪物/语音",
    tags: ["音效", "怪物", "语音", "咆哮", "战斗", "生物"],
    gameplay_features: ["怪物咆哮", "攻击声", "龙吼", "亡灵音效", "恶魔音效"]
  },
  {
    id: "sfx-magic-spells",
    title_en: "Magic Spells Sound Pack",
    title_zh: "魔法咒语音效包",
    category: "sfx",
    sub_category: "Magic/Spells",
    rating: 4.2,
    steam_rating: 85,
    price_cny: 52,
    price_cny_lowest: 42,
    steam_url: "https://store.steampowered.com/app/1728240/",
    steam_verified: true,
    steam_appid: "1728240",
    description: "魔法和咒语音效。火焰、冰霜、雷电、治愈、暗影等各系魔法施法和命中音效。丰富的魔法音效库。",
    review_summary: "魔法音效的优质来源。各元素魔法音效区分明显。让法术施放更有质感。",
    theme: "魔法/音效",
    tags: ["音效", "魔法", "咒语", "元素", "施法", "战斗"],
    gameplay_features: ["火焰音效", "冰霜音效", "雷电音效", "治愈音效", "暗影音效"]
  },
  {
    id: "sfx-ambient-nature",
    title_en: "Ambient Nature Sound Pack",
    title_zh: "自然环境音效包",
    category: "sfx",
    sub_category: "Ambient/Nature",
    rating: 4.1,
    steam_rating: 84,
    price_cny: 46,
    price_cny_lowest: 37,
    steam_url: "https://store.steampowered.com/app/3809000/RPG_Maker_MZ__Ambient_Nature_Sound_Pack/",
    steam_verified: false,
    steam_appid: "3809000",
    description: "自然环境氛围音效。森林鸟鸣、溪流、风声、雨声、虫鸣等自然场景音效。增强地图沉浸感。",
    review_summary: "自然氛围音效的基础包。森林场景的必备素材。沉浸感提升显著。",
    theme: "自然/氛围",
    tags: ["音效", "自然", "环境", "森林", "鸟鸣", "水流"],
    gameplay_features: ["森林氛围", "溪流声", "风声", "雨声", "虫鸣", "鸟鸣"]
  }
];

// Allow extending the data via external JSON
// Users can add their own DLC entries to a custom file
